// -------------------------------------------------------------
//
// Module: fir_20_32b_da
// Generated by MATLAB(R) 9.12 and Filter Design HDL Coder 3.1.11.
// Generated on: 2023-06-21 23:59:21
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// MultiplierInputPipeline: 1
// MultiplierOutputPipeline: 1
// OptimizeForHDL: on
// TargetDirectory: W:\Nikos\UTh\Σχεδίαση Επεξεργαστών\Project\FIR_20_Order\distributed_arithmetic\32b_floating_point
// AddPipelineRegisters: on
// Name: fir_20_32b_da
// DALUTPartition: [6  6  6  3]
// InputDataType: numerictype(1,32,0)
// TargetLanguage: Verilog
// TestBenchName: fir_20_32b_da_tb
// TestBenchStimulus: impulse step ramp chirp noise 

// Filter Specifications:
//
// Sample Rate     : 46 kHz
// Response        : Lowpass
// Specification   : N,Fp,Fst,Ap
// Stopband Edge   : 9.6 kHz
// Filter Order    : 20
// Passband Edge   : 8 kHz
// Passband Ripple : 60 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Distributed arithmetic (DA)
// Folding Factor        : 32
// LUT Address Width     : 6
// Total LUT Size (bits) : 6416
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 21
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s32,32 -> [-5.000000e-01 5.000000e-01)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module fir_20_32b_da
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [68:0] filter_out; //sfix69_En32

////////////////////////////////////////////////////////////////
//Module Architecture: fir_20_32b_da
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [31:0] coeff1 = 32'h00065332; //sfix32_En32
  parameter signed [31:0] coeff2 = 32'h00383D90; //sfix32_En32
  parameter signed [31:0] coeff3 = 32'h00FF1D6E; //sfix32_En32
  parameter signed [31:0] coeff4 = 32'h0327DFF2; //sfix32_En32
  parameter signed [31:0] coeff5 = 32'h07CD0ACB; //sfix32_En32
  parameter signed [31:0] coeff6 = 32'h0FEC18BB; //sfix32_En32
  parameter signed [31:0] coeff7 = 32'h1BB71D82; //sfix32_En32
  parameter signed [31:0] coeff8 = 32'h29FA0C85; //sfix32_En32
  parameter signed [31:0] coeff9 = 32'h3807CC7C; //sfix32_En32
  parameter signed [31:0] coeff10 = 32'h42701751; //sfix32_En32
  parameter signed [31:0] coeff11 = 32'h464995CD; //sfix32_En32
  parameter signed [31:0] coeff12 = 32'h42701751; //sfix32_En32
  parameter signed [31:0] coeff13 = 32'h3807CC7C; //sfix32_En32
  parameter signed [31:0] coeff14 = 32'h29FA0C85; //sfix32_En32
  parameter signed [31:0] coeff15 = 32'h1BB71D82; //sfix32_En32
  parameter signed [31:0] coeff16 = 32'h0FEC18BB; //sfix32_En32
  parameter signed [31:0] coeff17 = 32'h07CD0ACB; //sfix32_En32
  parameter signed [31:0] coeff18 = 32'h0327DFF2; //sfix32_En32
  parameter signed [31:0] coeff19 = 32'h00FF1D6E; //sfix32_En32
  parameter signed [31:0] coeff20 = 32'h00383D90; //sfix32_En32
  parameter signed [31:0] coeff21 = 32'h00065332; //sfix32_En32

  // Signals
  wire signed [31:0] filter_in_cast; // sfix32
  reg  [4:0] cur_count; // ufix5
  wire phase_31; // boolean
  wire phase_1; // boolean
  wire phase_2; // boolean
  wire serialoutb1; // ufix1
  reg  signed [31:0] shiftreg; // sfix32
  reg  delay_pipeline [0:639] ; // boolean
  wire [5:0] mem_addr_1; // ufix6
  reg  signed [29:0] memoutb1_1; // sfix30_En32
  wire [5:0] mem_addr_2; // ufix6
  reg  signed [33:0] memoutb1_2; // sfix34_En32
  wire [5:0] mem_addr_3; // ufix6
  reg  signed [32:0] memoutb1_3; // sfix33_En32
  wire [2:0] mem_addr_4; // ufix3
  reg  signed [25:0] memoutb1_4; // sfix26_En32
  wire signed [33:0] memoutb1; // sfix34_En32
  wire signed [34:0] sum1_1; // sfix35_En32
  wire signed [33:0] add_signext; // sfix34_En32
  wire signed [33:0] add_signext_1; // sfix34_En32
  reg  signed [34:0] sumpipe1_1; // sfix35_En32
  wire signed [33:0] sum1_2; // sfix34_En32
  wire signed [32:0] add_signext_2; // sfix33_En32
  wire signed [32:0] add_signext_3; // sfix33_En32
  reg  signed [33:0] sumpipe1_2; // sfix34_En32
  wire signed [35:0] sum2_1; // sfix36_En32
  wire signed [34:0] add_signext_4; // sfix35_En32
  wire signed [34:0] add_signext_5; // sfix35_En32
  reg  signed [35:0] sumpipe2_1; // sfix36_En32
  reg  signed [65:0] acc_out; // sfix66_En63
  wire signed [65:0] memoutb1_cast; // sfix66_En63
  wire signed [65:0] add_sub_out; // sfix66_En63
  wire signed [65:0] acc_out_shft; // sfix66_En63
  wire signed [65:0] acc_in; // sfix66_En63
  wire signed [65:0] addsub_add; // sfix66_En63
  wire signed [65:0] addsub_sub; // sfix66_En63
  wire signed [65:0] add_signext_6; // sfix66_En63
  wire signed [65:0] add_signext_7; // sfix66_En63
  wire signed [66:0] add_temp; // sfix67_En63
  wire signed [65:0] sub_signext; // sfix66_En63
  wire signed [65:0] sub_signext_1; // sfix66_En63
  wire signed [66:0] sub_temp; // sfix67_En63
  reg  signed [65:0] final_acc_out; // sfix66_En63
  wire signed [65:0] output_da; // sfix66_En32
  wire signed [68:0] output_typeconvert; // sfix69_En32
  reg  signed [68:0] output_register; // sfix69_En32

  // Block Statements
  assign filter_in_cast = filter_in;

  always @ (posedge clk or posedge reset)
    begin: Counter_process
      if (reset == 1'b1) begin
        cur_count <= 5'b11111;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 5'b11111) begin
            cur_count <= 5'b00000;
          end
          else begin
            cur_count <= cur_count + 5'b00001;
          end
        end
      end
    end // Counter_process

  assign  phase_31 = (cur_count == 5'b11111 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_1 = (cur_count == 5'b00001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign  phase_2 = (cur_count == 5'b00010 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: Serializer_1_process
      if (reset == 1'b1) begin
        shiftreg <= 32'h00000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (phase_31 == 1'b1) begin
            shiftreg <= filter_in_cast;
          end
          else begin
            shiftreg <= {1'b0, shiftreg[31 : 1]};
          end
        end
      end 
    end // Serializer_1_process;

  assign   serialoutb1=shiftreg[0];
 
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_1_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 1'b0;
        delay_pipeline[1] <= 1'b0;
        delay_pipeline[2] <= 1'b0;
        delay_pipeline[3] <= 1'b0;
        delay_pipeline[4] <= 1'b0;
        delay_pipeline[5] <= 1'b0;
        delay_pipeline[6] <= 1'b0;
        delay_pipeline[7] <= 1'b0;
        delay_pipeline[8] <= 1'b0;
        delay_pipeline[9] <= 1'b0;
        delay_pipeline[10] <= 1'b0;
        delay_pipeline[11] <= 1'b0;
        delay_pipeline[12] <= 1'b0;
        delay_pipeline[13] <= 1'b0;
        delay_pipeline[14] <= 1'b0;
        delay_pipeline[15] <= 1'b0;
        delay_pipeline[16] <= 1'b0;
        delay_pipeline[17] <= 1'b0;
        delay_pipeline[18] <= 1'b0;
        delay_pipeline[19] <= 1'b0;
        delay_pipeline[20] <= 1'b0;
        delay_pipeline[21] <= 1'b0;
        delay_pipeline[22] <= 1'b0;
        delay_pipeline[23] <= 1'b0;
        delay_pipeline[24] <= 1'b0;
        delay_pipeline[25] <= 1'b0;
        delay_pipeline[26] <= 1'b0;
        delay_pipeline[27] <= 1'b0;
        delay_pipeline[28] <= 1'b0;
        delay_pipeline[29] <= 1'b0;
        delay_pipeline[30] <= 1'b0;
        delay_pipeline[31] <= 1'b0;
        delay_pipeline[32] <= 1'b0;
        delay_pipeline[33] <= 1'b0;
        delay_pipeline[34] <= 1'b0;
        delay_pipeline[35] <= 1'b0;
        delay_pipeline[36] <= 1'b0;
        delay_pipeline[37] <= 1'b0;
        delay_pipeline[38] <= 1'b0;
        delay_pipeline[39] <= 1'b0;
        delay_pipeline[40] <= 1'b0;
        delay_pipeline[41] <= 1'b0;
        delay_pipeline[42] <= 1'b0;
        delay_pipeline[43] <= 1'b0;
        delay_pipeline[44] <= 1'b0;
        delay_pipeline[45] <= 1'b0;
        delay_pipeline[46] <= 1'b0;
        delay_pipeline[47] <= 1'b0;
        delay_pipeline[48] <= 1'b0;
        delay_pipeline[49] <= 1'b0;
        delay_pipeline[50] <= 1'b0;
        delay_pipeline[51] <= 1'b0;
        delay_pipeline[52] <= 1'b0;
        delay_pipeline[53] <= 1'b0;
        delay_pipeline[54] <= 1'b0;
        delay_pipeline[55] <= 1'b0;
        delay_pipeline[56] <= 1'b0;
        delay_pipeline[57] <= 1'b0;
        delay_pipeline[58] <= 1'b0;
        delay_pipeline[59] <= 1'b0;
        delay_pipeline[60] <= 1'b0;
        delay_pipeline[61] <= 1'b0;
        delay_pipeline[62] <= 1'b0;
        delay_pipeline[63] <= 1'b0;
        delay_pipeline[64] <= 1'b0;
        delay_pipeline[65] <= 1'b0;
        delay_pipeline[66] <= 1'b0;
        delay_pipeline[67] <= 1'b0;
        delay_pipeline[68] <= 1'b0;
        delay_pipeline[69] <= 1'b0;
        delay_pipeline[70] <= 1'b0;
        delay_pipeline[71] <= 1'b0;
        delay_pipeline[72] <= 1'b0;
        delay_pipeline[73] <= 1'b0;
        delay_pipeline[74] <= 1'b0;
        delay_pipeline[75] <= 1'b0;
        delay_pipeline[76] <= 1'b0;
        delay_pipeline[77] <= 1'b0;
        delay_pipeline[78] <= 1'b0;
        delay_pipeline[79] <= 1'b0;
        delay_pipeline[80] <= 1'b0;
        delay_pipeline[81] <= 1'b0;
        delay_pipeline[82] <= 1'b0;
        delay_pipeline[83] <= 1'b0;
        delay_pipeline[84] <= 1'b0;
        delay_pipeline[85] <= 1'b0;
        delay_pipeline[86] <= 1'b0;
        delay_pipeline[87] <= 1'b0;
        delay_pipeline[88] <= 1'b0;
        delay_pipeline[89] <= 1'b0;
        delay_pipeline[90] <= 1'b0;
        delay_pipeline[91] <= 1'b0;
        delay_pipeline[92] <= 1'b0;
        delay_pipeline[93] <= 1'b0;
        delay_pipeline[94] <= 1'b0;
        delay_pipeline[95] <= 1'b0;
        delay_pipeline[96] <= 1'b0;
        delay_pipeline[97] <= 1'b0;
        delay_pipeline[98] <= 1'b0;
        delay_pipeline[99] <= 1'b0;
        delay_pipeline[100] <= 1'b0;
        delay_pipeline[101] <= 1'b0;
        delay_pipeline[102] <= 1'b0;
        delay_pipeline[103] <= 1'b0;
        delay_pipeline[104] <= 1'b0;
        delay_pipeline[105] <= 1'b0;
        delay_pipeline[106] <= 1'b0;
        delay_pipeline[107] <= 1'b0;
        delay_pipeline[108] <= 1'b0;
        delay_pipeline[109] <= 1'b0;
        delay_pipeline[110] <= 1'b0;
        delay_pipeline[111] <= 1'b0;
        delay_pipeline[112] <= 1'b0;
        delay_pipeline[113] <= 1'b0;
        delay_pipeline[114] <= 1'b0;
        delay_pipeline[115] <= 1'b0;
        delay_pipeline[116] <= 1'b0;
        delay_pipeline[117] <= 1'b0;
        delay_pipeline[118] <= 1'b0;
        delay_pipeline[119] <= 1'b0;
        delay_pipeline[120] <= 1'b0;
        delay_pipeline[121] <= 1'b0;
        delay_pipeline[122] <= 1'b0;
        delay_pipeline[123] <= 1'b0;
        delay_pipeline[124] <= 1'b0;
        delay_pipeline[125] <= 1'b0;
        delay_pipeline[126] <= 1'b0;
        delay_pipeline[127] <= 1'b0;
        delay_pipeline[128] <= 1'b0;
        delay_pipeline[129] <= 1'b0;
        delay_pipeline[130] <= 1'b0;
        delay_pipeline[131] <= 1'b0;
        delay_pipeline[132] <= 1'b0;
        delay_pipeline[133] <= 1'b0;
        delay_pipeline[134] <= 1'b0;
        delay_pipeline[135] <= 1'b0;
        delay_pipeline[136] <= 1'b0;
        delay_pipeline[137] <= 1'b0;
        delay_pipeline[138] <= 1'b0;
        delay_pipeline[139] <= 1'b0;
        delay_pipeline[140] <= 1'b0;
        delay_pipeline[141] <= 1'b0;
        delay_pipeline[142] <= 1'b0;
        delay_pipeline[143] <= 1'b0;
        delay_pipeline[144] <= 1'b0;
        delay_pipeline[145] <= 1'b0;
        delay_pipeline[146] <= 1'b0;
        delay_pipeline[147] <= 1'b0;
        delay_pipeline[148] <= 1'b0;
        delay_pipeline[149] <= 1'b0;
        delay_pipeline[150] <= 1'b0;
        delay_pipeline[151] <= 1'b0;
        delay_pipeline[152] <= 1'b0;
        delay_pipeline[153] <= 1'b0;
        delay_pipeline[154] <= 1'b0;
        delay_pipeline[155] <= 1'b0;
        delay_pipeline[156] <= 1'b0;
        delay_pipeline[157] <= 1'b0;
        delay_pipeline[158] <= 1'b0;
        delay_pipeline[159] <= 1'b0;
        delay_pipeline[160] <= 1'b0;
        delay_pipeline[161] <= 1'b0;
        delay_pipeline[162] <= 1'b0;
        delay_pipeline[163] <= 1'b0;
        delay_pipeline[164] <= 1'b0;
        delay_pipeline[165] <= 1'b0;
        delay_pipeline[166] <= 1'b0;
        delay_pipeline[167] <= 1'b0;
        delay_pipeline[168] <= 1'b0;
        delay_pipeline[169] <= 1'b0;
        delay_pipeline[170] <= 1'b0;
        delay_pipeline[171] <= 1'b0;
        delay_pipeline[172] <= 1'b0;
        delay_pipeline[173] <= 1'b0;
        delay_pipeline[174] <= 1'b0;
        delay_pipeline[175] <= 1'b0;
        delay_pipeline[176] <= 1'b0;
        delay_pipeline[177] <= 1'b0;
        delay_pipeline[178] <= 1'b0;
        delay_pipeline[179] <= 1'b0;
        delay_pipeline[180] <= 1'b0;
        delay_pipeline[181] <= 1'b0;
        delay_pipeline[182] <= 1'b0;
        delay_pipeline[183] <= 1'b0;
        delay_pipeline[184] <= 1'b0;
        delay_pipeline[185] <= 1'b0;
        delay_pipeline[186] <= 1'b0;
        delay_pipeline[187] <= 1'b0;
        delay_pipeline[188] <= 1'b0;
        delay_pipeline[189] <= 1'b0;
        delay_pipeline[190] <= 1'b0;
        delay_pipeline[191] <= 1'b0;
        delay_pipeline[192] <= 1'b0;
        delay_pipeline[193] <= 1'b0;
        delay_pipeline[194] <= 1'b0;
        delay_pipeline[195] <= 1'b0;
        delay_pipeline[196] <= 1'b0;
        delay_pipeline[197] <= 1'b0;
        delay_pipeline[198] <= 1'b0;
        delay_pipeline[199] <= 1'b0;
        delay_pipeline[200] <= 1'b0;
        delay_pipeline[201] <= 1'b0;
        delay_pipeline[202] <= 1'b0;
        delay_pipeline[203] <= 1'b0;
        delay_pipeline[204] <= 1'b0;
        delay_pipeline[205] <= 1'b0;
        delay_pipeline[206] <= 1'b0;
        delay_pipeline[207] <= 1'b0;
        delay_pipeline[208] <= 1'b0;
        delay_pipeline[209] <= 1'b0;
        delay_pipeline[210] <= 1'b0;
        delay_pipeline[211] <= 1'b0;
        delay_pipeline[212] <= 1'b0;
        delay_pipeline[213] <= 1'b0;
        delay_pipeline[214] <= 1'b0;
        delay_pipeline[215] <= 1'b0;
        delay_pipeline[216] <= 1'b0;
        delay_pipeline[217] <= 1'b0;
        delay_pipeline[218] <= 1'b0;
        delay_pipeline[219] <= 1'b0;
        delay_pipeline[220] <= 1'b0;
        delay_pipeline[221] <= 1'b0;
        delay_pipeline[222] <= 1'b0;
        delay_pipeline[223] <= 1'b0;
        delay_pipeline[224] <= 1'b0;
        delay_pipeline[225] <= 1'b0;
        delay_pipeline[226] <= 1'b0;
        delay_pipeline[227] <= 1'b0;
        delay_pipeline[228] <= 1'b0;
        delay_pipeline[229] <= 1'b0;
        delay_pipeline[230] <= 1'b0;
        delay_pipeline[231] <= 1'b0;
        delay_pipeline[232] <= 1'b0;
        delay_pipeline[233] <= 1'b0;
        delay_pipeline[234] <= 1'b0;
        delay_pipeline[235] <= 1'b0;
        delay_pipeline[236] <= 1'b0;
        delay_pipeline[237] <= 1'b0;
        delay_pipeline[238] <= 1'b0;
        delay_pipeline[239] <= 1'b0;
        delay_pipeline[240] <= 1'b0;
        delay_pipeline[241] <= 1'b0;
        delay_pipeline[242] <= 1'b0;
        delay_pipeline[243] <= 1'b0;
        delay_pipeline[244] <= 1'b0;
        delay_pipeline[245] <= 1'b0;
        delay_pipeline[246] <= 1'b0;
        delay_pipeline[247] <= 1'b0;
        delay_pipeline[248] <= 1'b0;
        delay_pipeline[249] <= 1'b0;
        delay_pipeline[250] <= 1'b0;
        delay_pipeline[251] <= 1'b0;
        delay_pipeline[252] <= 1'b0;
        delay_pipeline[253] <= 1'b0;
        delay_pipeline[254] <= 1'b0;
        delay_pipeline[255] <= 1'b0;
        delay_pipeline[256] <= 1'b0;
        delay_pipeline[257] <= 1'b0;
        delay_pipeline[258] <= 1'b0;
        delay_pipeline[259] <= 1'b0;
        delay_pipeline[260] <= 1'b0;
        delay_pipeline[261] <= 1'b0;
        delay_pipeline[262] <= 1'b0;
        delay_pipeline[263] <= 1'b0;
        delay_pipeline[264] <= 1'b0;
        delay_pipeline[265] <= 1'b0;
        delay_pipeline[266] <= 1'b0;
        delay_pipeline[267] <= 1'b0;
        delay_pipeline[268] <= 1'b0;
        delay_pipeline[269] <= 1'b0;
        delay_pipeline[270] <= 1'b0;
        delay_pipeline[271] <= 1'b0;
        delay_pipeline[272] <= 1'b0;
        delay_pipeline[273] <= 1'b0;
        delay_pipeline[274] <= 1'b0;
        delay_pipeline[275] <= 1'b0;
        delay_pipeline[276] <= 1'b0;
        delay_pipeline[277] <= 1'b0;
        delay_pipeline[278] <= 1'b0;
        delay_pipeline[279] <= 1'b0;
        delay_pipeline[280] <= 1'b0;
        delay_pipeline[281] <= 1'b0;
        delay_pipeline[282] <= 1'b0;
        delay_pipeline[283] <= 1'b0;
        delay_pipeline[284] <= 1'b0;
        delay_pipeline[285] <= 1'b0;
        delay_pipeline[286] <= 1'b0;
        delay_pipeline[287] <= 1'b0;
        delay_pipeline[288] <= 1'b0;
        delay_pipeline[289] <= 1'b0;
        delay_pipeline[290] <= 1'b0;
        delay_pipeline[291] <= 1'b0;
        delay_pipeline[292] <= 1'b0;
        delay_pipeline[293] <= 1'b0;
        delay_pipeline[294] <= 1'b0;
        delay_pipeline[295] <= 1'b0;
        delay_pipeline[296] <= 1'b0;
        delay_pipeline[297] <= 1'b0;
        delay_pipeline[298] <= 1'b0;
        delay_pipeline[299] <= 1'b0;
        delay_pipeline[300] <= 1'b0;
        delay_pipeline[301] <= 1'b0;
        delay_pipeline[302] <= 1'b0;
        delay_pipeline[303] <= 1'b0;
        delay_pipeline[304] <= 1'b0;
        delay_pipeline[305] <= 1'b0;
        delay_pipeline[306] <= 1'b0;
        delay_pipeline[307] <= 1'b0;
        delay_pipeline[308] <= 1'b0;
        delay_pipeline[309] <= 1'b0;
        delay_pipeline[310] <= 1'b0;
        delay_pipeline[311] <= 1'b0;
        delay_pipeline[312] <= 1'b0;
        delay_pipeline[313] <= 1'b0;
        delay_pipeline[314] <= 1'b0;
        delay_pipeline[315] <= 1'b0;
        delay_pipeline[316] <= 1'b0;
        delay_pipeline[317] <= 1'b0;
        delay_pipeline[318] <= 1'b0;
        delay_pipeline[319] <= 1'b0;
        delay_pipeline[320] <= 1'b0;
        delay_pipeline[321] <= 1'b0;
        delay_pipeline[322] <= 1'b0;
        delay_pipeline[323] <= 1'b0;
        delay_pipeline[324] <= 1'b0;
        delay_pipeline[325] <= 1'b0;
        delay_pipeline[326] <= 1'b0;
        delay_pipeline[327] <= 1'b0;
        delay_pipeline[328] <= 1'b0;
        delay_pipeline[329] <= 1'b0;
        delay_pipeline[330] <= 1'b0;
        delay_pipeline[331] <= 1'b0;
        delay_pipeline[332] <= 1'b0;
        delay_pipeline[333] <= 1'b0;
        delay_pipeline[334] <= 1'b0;
        delay_pipeline[335] <= 1'b0;
        delay_pipeline[336] <= 1'b0;
        delay_pipeline[337] <= 1'b0;
        delay_pipeline[338] <= 1'b0;
        delay_pipeline[339] <= 1'b0;
        delay_pipeline[340] <= 1'b0;
        delay_pipeline[341] <= 1'b0;
        delay_pipeline[342] <= 1'b0;
        delay_pipeline[343] <= 1'b0;
        delay_pipeline[344] <= 1'b0;
        delay_pipeline[345] <= 1'b0;
        delay_pipeline[346] <= 1'b0;
        delay_pipeline[347] <= 1'b0;
        delay_pipeline[348] <= 1'b0;
        delay_pipeline[349] <= 1'b0;
        delay_pipeline[350] <= 1'b0;
        delay_pipeline[351] <= 1'b0;
        delay_pipeline[352] <= 1'b0;
        delay_pipeline[353] <= 1'b0;
        delay_pipeline[354] <= 1'b0;
        delay_pipeline[355] <= 1'b0;
        delay_pipeline[356] <= 1'b0;
        delay_pipeline[357] <= 1'b0;
        delay_pipeline[358] <= 1'b0;
        delay_pipeline[359] <= 1'b0;
        delay_pipeline[360] <= 1'b0;
        delay_pipeline[361] <= 1'b0;
        delay_pipeline[362] <= 1'b0;
        delay_pipeline[363] <= 1'b0;
        delay_pipeline[364] <= 1'b0;
        delay_pipeline[365] <= 1'b0;
        delay_pipeline[366] <= 1'b0;
        delay_pipeline[367] <= 1'b0;
        delay_pipeline[368] <= 1'b0;
        delay_pipeline[369] <= 1'b0;
        delay_pipeline[370] <= 1'b0;
        delay_pipeline[371] <= 1'b0;
        delay_pipeline[372] <= 1'b0;
        delay_pipeline[373] <= 1'b0;
        delay_pipeline[374] <= 1'b0;
        delay_pipeline[375] <= 1'b0;
        delay_pipeline[376] <= 1'b0;
        delay_pipeline[377] <= 1'b0;
        delay_pipeline[378] <= 1'b0;
        delay_pipeline[379] <= 1'b0;
        delay_pipeline[380] <= 1'b0;
        delay_pipeline[381] <= 1'b0;
        delay_pipeline[382] <= 1'b0;
        delay_pipeline[383] <= 1'b0;
        delay_pipeline[384] <= 1'b0;
        delay_pipeline[385] <= 1'b0;
        delay_pipeline[386] <= 1'b0;
        delay_pipeline[387] <= 1'b0;
        delay_pipeline[388] <= 1'b0;
        delay_pipeline[389] <= 1'b0;
        delay_pipeline[390] <= 1'b0;
        delay_pipeline[391] <= 1'b0;
        delay_pipeline[392] <= 1'b0;
        delay_pipeline[393] <= 1'b0;
        delay_pipeline[394] <= 1'b0;
        delay_pipeline[395] <= 1'b0;
        delay_pipeline[396] <= 1'b0;
        delay_pipeline[397] <= 1'b0;
        delay_pipeline[398] <= 1'b0;
        delay_pipeline[399] <= 1'b0;
        delay_pipeline[400] <= 1'b0;
        delay_pipeline[401] <= 1'b0;
        delay_pipeline[402] <= 1'b0;
        delay_pipeline[403] <= 1'b0;
        delay_pipeline[404] <= 1'b0;
        delay_pipeline[405] <= 1'b0;
        delay_pipeline[406] <= 1'b0;
        delay_pipeline[407] <= 1'b0;
        delay_pipeline[408] <= 1'b0;
        delay_pipeline[409] <= 1'b0;
        delay_pipeline[410] <= 1'b0;
        delay_pipeline[411] <= 1'b0;
        delay_pipeline[412] <= 1'b0;
        delay_pipeline[413] <= 1'b0;
        delay_pipeline[414] <= 1'b0;
        delay_pipeline[415] <= 1'b0;
        delay_pipeline[416] <= 1'b0;
        delay_pipeline[417] <= 1'b0;
        delay_pipeline[418] <= 1'b0;
        delay_pipeline[419] <= 1'b0;
        delay_pipeline[420] <= 1'b0;
        delay_pipeline[421] <= 1'b0;
        delay_pipeline[422] <= 1'b0;
        delay_pipeline[423] <= 1'b0;
        delay_pipeline[424] <= 1'b0;
        delay_pipeline[425] <= 1'b0;
        delay_pipeline[426] <= 1'b0;
        delay_pipeline[427] <= 1'b0;
        delay_pipeline[428] <= 1'b0;
        delay_pipeline[429] <= 1'b0;
        delay_pipeline[430] <= 1'b0;
        delay_pipeline[431] <= 1'b0;
        delay_pipeline[432] <= 1'b0;
        delay_pipeline[433] <= 1'b0;
        delay_pipeline[434] <= 1'b0;
        delay_pipeline[435] <= 1'b0;
        delay_pipeline[436] <= 1'b0;
        delay_pipeline[437] <= 1'b0;
        delay_pipeline[438] <= 1'b0;
        delay_pipeline[439] <= 1'b0;
        delay_pipeline[440] <= 1'b0;
        delay_pipeline[441] <= 1'b0;
        delay_pipeline[442] <= 1'b0;
        delay_pipeline[443] <= 1'b0;
        delay_pipeline[444] <= 1'b0;
        delay_pipeline[445] <= 1'b0;
        delay_pipeline[446] <= 1'b0;
        delay_pipeline[447] <= 1'b0;
        delay_pipeline[448] <= 1'b0;
        delay_pipeline[449] <= 1'b0;
        delay_pipeline[450] <= 1'b0;
        delay_pipeline[451] <= 1'b0;
        delay_pipeline[452] <= 1'b0;
        delay_pipeline[453] <= 1'b0;
        delay_pipeline[454] <= 1'b0;
        delay_pipeline[455] <= 1'b0;
        delay_pipeline[456] <= 1'b0;
        delay_pipeline[457] <= 1'b0;
        delay_pipeline[458] <= 1'b0;
        delay_pipeline[459] <= 1'b0;
        delay_pipeline[460] <= 1'b0;
        delay_pipeline[461] <= 1'b0;
        delay_pipeline[462] <= 1'b0;
        delay_pipeline[463] <= 1'b0;
        delay_pipeline[464] <= 1'b0;
        delay_pipeline[465] <= 1'b0;
        delay_pipeline[466] <= 1'b0;
        delay_pipeline[467] <= 1'b0;
        delay_pipeline[468] <= 1'b0;
        delay_pipeline[469] <= 1'b0;
        delay_pipeline[470] <= 1'b0;
        delay_pipeline[471] <= 1'b0;
        delay_pipeline[472] <= 1'b0;
        delay_pipeline[473] <= 1'b0;
        delay_pipeline[474] <= 1'b0;
        delay_pipeline[475] <= 1'b0;
        delay_pipeline[476] <= 1'b0;
        delay_pipeline[477] <= 1'b0;
        delay_pipeline[478] <= 1'b0;
        delay_pipeline[479] <= 1'b0;
        delay_pipeline[480] <= 1'b0;
        delay_pipeline[481] <= 1'b0;
        delay_pipeline[482] <= 1'b0;
        delay_pipeline[483] <= 1'b0;
        delay_pipeline[484] <= 1'b0;
        delay_pipeline[485] <= 1'b0;
        delay_pipeline[486] <= 1'b0;
        delay_pipeline[487] <= 1'b0;
        delay_pipeline[488] <= 1'b0;
        delay_pipeline[489] <= 1'b0;
        delay_pipeline[490] <= 1'b0;
        delay_pipeline[491] <= 1'b0;
        delay_pipeline[492] <= 1'b0;
        delay_pipeline[493] <= 1'b0;
        delay_pipeline[494] <= 1'b0;
        delay_pipeline[495] <= 1'b0;
        delay_pipeline[496] <= 1'b0;
        delay_pipeline[497] <= 1'b0;
        delay_pipeline[498] <= 1'b0;
        delay_pipeline[499] <= 1'b0;
        delay_pipeline[500] <= 1'b0;
        delay_pipeline[501] <= 1'b0;
        delay_pipeline[502] <= 1'b0;
        delay_pipeline[503] <= 1'b0;
        delay_pipeline[504] <= 1'b0;
        delay_pipeline[505] <= 1'b0;
        delay_pipeline[506] <= 1'b0;
        delay_pipeline[507] <= 1'b0;
        delay_pipeline[508] <= 1'b0;
        delay_pipeline[509] <= 1'b0;
        delay_pipeline[510] <= 1'b0;
        delay_pipeline[511] <= 1'b0;
        delay_pipeline[512] <= 1'b0;
        delay_pipeline[513] <= 1'b0;
        delay_pipeline[514] <= 1'b0;
        delay_pipeline[515] <= 1'b0;
        delay_pipeline[516] <= 1'b0;
        delay_pipeline[517] <= 1'b0;
        delay_pipeline[518] <= 1'b0;
        delay_pipeline[519] <= 1'b0;
        delay_pipeline[520] <= 1'b0;
        delay_pipeline[521] <= 1'b0;
        delay_pipeline[522] <= 1'b0;
        delay_pipeline[523] <= 1'b0;
        delay_pipeline[524] <= 1'b0;
        delay_pipeline[525] <= 1'b0;
        delay_pipeline[526] <= 1'b0;
        delay_pipeline[527] <= 1'b0;
        delay_pipeline[528] <= 1'b0;
        delay_pipeline[529] <= 1'b0;
        delay_pipeline[530] <= 1'b0;
        delay_pipeline[531] <= 1'b0;
        delay_pipeline[532] <= 1'b0;
        delay_pipeline[533] <= 1'b0;
        delay_pipeline[534] <= 1'b0;
        delay_pipeline[535] <= 1'b0;
        delay_pipeline[536] <= 1'b0;
        delay_pipeline[537] <= 1'b0;
        delay_pipeline[538] <= 1'b0;
        delay_pipeline[539] <= 1'b0;
        delay_pipeline[540] <= 1'b0;
        delay_pipeline[541] <= 1'b0;
        delay_pipeline[542] <= 1'b0;
        delay_pipeline[543] <= 1'b0;
        delay_pipeline[544] <= 1'b0;
        delay_pipeline[545] <= 1'b0;
        delay_pipeline[546] <= 1'b0;
        delay_pipeline[547] <= 1'b0;
        delay_pipeline[548] <= 1'b0;
        delay_pipeline[549] <= 1'b0;
        delay_pipeline[550] <= 1'b0;
        delay_pipeline[551] <= 1'b0;
        delay_pipeline[552] <= 1'b0;
        delay_pipeline[553] <= 1'b0;
        delay_pipeline[554] <= 1'b0;
        delay_pipeline[555] <= 1'b0;
        delay_pipeline[556] <= 1'b0;
        delay_pipeline[557] <= 1'b0;
        delay_pipeline[558] <= 1'b0;
        delay_pipeline[559] <= 1'b0;
        delay_pipeline[560] <= 1'b0;
        delay_pipeline[561] <= 1'b0;
        delay_pipeline[562] <= 1'b0;
        delay_pipeline[563] <= 1'b0;
        delay_pipeline[564] <= 1'b0;
        delay_pipeline[565] <= 1'b0;
        delay_pipeline[566] <= 1'b0;
        delay_pipeline[567] <= 1'b0;
        delay_pipeline[568] <= 1'b0;
        delay_pipeline[569] <= 1'b0;
        delay_pipeline[570] <= 1'b0;
        delay_pipeline[571] <= 1'b0;
        delay_pipeline[572] <= 1'b0;
        delay_pipeline[573] <= 1'b0;
        delay_pipeline[574] <= 1'b0;
        delay_pipeline[575] <= 1'b0;
        delay_pipeline[576] <= 1'b0;
        delay_pipeline[577] <= 1'b0;
        delay_pipeline[578] <= 1'b0;
        delay_pipeline[579] <= 1'b0;
        delay_pipeline[580] <= 1'b0;
        delay_pipeline[581] <= 1'b0;
        delay_pipeline[582] <= 1'b0;
        delay_pipeline[583] <= 1'b0;
        delay_pipeline[584] <= 1'b0;
        delay_pipeline[585] <= 1'b0;
        delay_pipeline[586] <= 1'b0;
        delay_pipeline[587] <= 1'b0;
        delay_pipeline[588] <= 1'b0;
        delay_pipeline[589] <= 1'b0;
        delay_pipeline[590] <= 1'b0;
        delay_pipeline[591] <= 1'b0;
        delay_pipeline[592] <= 1'b0;
        delay_pipeline[593] <= 1'b0;
        delay_pipeline[594] <= 1'b0;
        delay_pipeline[595] <= 1'b0;
        delay_pipeline[596] <= 1'b0;
        delay_pipeline[597] <= 1'b0;
        delay_pipeline[598] <= 1'b0;
        delay_pipeline[599] <= 1'b0;
        delay_pipeline[600] <= 1'b0;
        delay_pipeline[601] <= 1'b0;
        delay_pipeline[602] <= 1'b0;
        delay_pipeline[603] <= 1'b0;
        delay_pipeline[604] <= 1'b0;
        delay_pipeline[605] <= 1'b0;
        delay_pipeline[606] <= 1'b0;
        delay_pipeline[607] <= 1'b0;
        delay_pipeline[608] <= 1'b0;
        delay_pipeline[609] <= 1'b0;
        delay_pipeline[610] <= 1'b0;
        delay_pipeline[611] <= 1'b0;
        delay_pipeline[612] <= 1'b0;
        delay_pipeline[613] <= 1'b0;
        delay_pipeline[614] <= 1'b0;
        delay_pipeline[615] <= 1'b0;
        delay_pipeline[616] <= 1'b0;
        delay_pipeline[617] <= 1'b0;
        delay_pipeline[618] <= 1'b0;
        delay_pipeline[619] <= 1'b0;
        delay_pipeline[620] <= 1'b0;
        delay_pipeline[621] <= 1'b0;
        delay_pipeline[622] <= 1'b0;
        delay_pipeline[623] <= 1'b0;
        delay_pipeline[624] <= 1'b0;
        delay_pipeline[625] <= 1'b0;
        delay_pipeline[626] <= 1'b0;
        delay_pipeline[627] <= 1'b0;
        delay_pipeline[628] <= 1'b0;
        delay_pipeline[629] <= 1'b0;
        delay_pipeline[630] <= 1'b0;
        delay_pipeline[631] <= 1'b0;
        delay_pipeline[632] <= 1'b0;
        delay_pipeline[633] <= 1'b0;
        delay_pipeline[634] <= 1'b0;
        delay_pipeline[635] <= 1'b0;
        delay_pipeline[636] <= 1'b0;
        delay_pipeline[637] <= 1'b0;
        delay_pipeline[638] <= 1'b0;
        delay_pipeline[639] <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= serialoutb1;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
          delay_pipeline[43] <= delay_pipeline[42];
          delay_pipeline[44] <= delay_pipeline[43];
          delay_pipeline[45] <= delay_pipeline[44];
          delay_pipeline[46] <= delay_pipeline[45];
          delay_pipeline[47] <= delay_pipeline[46];
          delay_pipeline[48] <= delay_pipeline[47];
          delay_pipeline[49] <= delay_pipeline[48];
          delay_pipeline[50] <= delay_pipeline[49];
          delay_pipeline[51] <= delay_pipeline[50];
          delay_pipeline[52] <= delay_pipeline[51];
          delay_pipeline[53] <= delay_pipeline[52];
          delay_pipeline[54] <= delay_pipeline[53];
          delay_pipeline[55] <= delay_pipeline[54];
          delay_pipeline[56] <= delay_pipeline[55];
          delay_pipeline[57] <= delay_pipeline[56];
          delay_pipeline[58] <= delay_pipeline[57];
          delay_pipeline[59] <= delay_pipeline[58];
          delay_pipeline[60] <= delay_pipeline[59];
          delay_pipeline[61] <= delay_pipeline[60];
          delay_pipeline[62] <= delay_pipeline[61];
          delay_pipeline[63] <= delay_pipeline[62];
          delay_pipeline[64] <= delay_pipeline[63];
          delay_pipeline[65] <= delay_pipeline[64];
          delay_pipeline[66] <= delay_pipeline[65];
          delay_pipeline[67] <= delay_pipeline[66];
          delay_pipeline[68] <= delay_pipeline[67];
          delay_pipeline[69] <= delay_pipeline[68];
          delay_pipeline[70] <= delay_pipeline[69];
          delay_pipeline[71] <= delay_pipeline[70];
          delay_pipeline[72] <= delay_pipeline[71];
          delay_pipeline[73] <= delay_pipeline[72];
          delay_pipeline[74] <= delay_pipeline[73];
          delay_pipeline[75] <= delay_pipeline[74];
          delay_pipeline[76] <= delay_pipeline[75];
          delay_pipeline[77] <= delay_pipeline[76];
          delay_pipeline[78] <= delay_pipeline[77];
          delay_pipeline[79] <= delay_pipeline[78];
          delay_pipeline[80] <= delay_pipeline[79];
          delay_pipeline[81] <= delay_pipeline[80];
          delay_pipeline[82] <= delay_pipeline[81];
          delay_pipeline[83] <= delay_pipeline[82];
          delay_pipeline[84] <= delay_pipeline[83];
          delay_pipeline[85] <= delay_pipeline[84];
          delay_pipeline[86] <= delay_pipeline[85];
          delay_pipeline[87] <= delay_pipeline[86];
          delay_pipeline[88] <= delay_pipeline[87];
          delay_pipeline[89] <= delay_pipeline[88];
          delay_pipeline[90] <= delay_pipeline[89];
          delay_pipeline[91] <= delay_pipeline[90];
          delay_pipeline[92] <= delay_pipeline[91];
          delay_pipeline[93] <= delay_pipeline[92];
          delay_pipeline[94] <= delay_pipeline[93];
          delay_pipeline[95] <= delay_pipeline[94];
          delay_pipeline[96] <= delay_pipeline[95];
          delay_pipeline[97] <= delay_pipeline[96];
          delay_pipeline[98] <= delay_pipeline[97];
          delay_pipeline[99] <= delay_pipeline[98];
          delay_pipeline[100] <= delay_pipeline[99];
          delay_pipeline[101] <= delay_pipeline[100];
          delay_pipeline[102] <= delay_pipeline[101];
          delay_pipeline[103] <= delay_pipeline[102];
          delay_pipeline[104] <= delay_pipeline[103];
          delay_pipeline[105] <= delay_pipeline[104];
          delay_pipeline[106] <= delay_pipeline[105];
          delay_pipeline[107] <= delay_pipeline[106];
          delay_pipeline[108] <= delay_pipeline[107];
          delay_pipeline[109] <= delay_pipeline[108];
          delay_pipeline[110] <= delay_pipeline[109];
          delay_pipeline[111] <= delay_pipeline[110];
          delay_pipeline[112] <= delay_pipeline[111];
          delay_pipeline[113] <= delay_pipeline[112];
          delay_pipeline[114] <= delay_pipeline[113];
          delay_pipeline[115] <= delay_pipeline[114];
          delay_pipeline[116] <= delay_pipeline[115];
          delay_pipeline[117] <= delay_pipeline[116];
          delay_pipeline[118] <= delay_pipeline[117];
          delay_pipeline[119] <= delay_pipeline[118];
          delay_pipeline[120] <= delay_pipeline[119];
          delay_pipeline[121] <= delay_pipeline[120];
          delay_pipeline[122] <= delay_pipeline[121];
          delay_pipeline[123] <= delay_pipeline[122];
          delay_pipeline[124] <= delay_pipeline[123];
          delay_pipeline[125] <= delay_pipeline[124];
          delay_pipeline[126] <= delay_pipeline[125];
          delay_pipeline[127] <= delay_pipeline[126];
          delay_pipeline[128] <= delay_pipeline[127];
          delay_pipeline[129] <= delay_pipeline[128];
          delay_pipeline[130] <= delay_pipeline[129];
          delay_pipeline[131] <= delay_pipeline[130];
          delay_pipeline[132] <= delay_pipeline[131];
          delay_pipeline[133] <= delay_pipeline[132];
          delay_pipeline[134] <= delay_pipeline[133];
          delay_pipeline[135] <= delay_pipeline[134];
          delay_pipeline[136] <= delay_pipeline[135];
          delay_pipeline[137] <= delay_pipeline[136];
          delay_pipeline[138] <= delay_pipeline[137];
          delay_pipeline[139] <= delay_pipeline[138];
          delay_pipeline[140] <= delay_pipeline[139];
          delay_pipeline[141] <= delay_pipeline[140];
          delay_pipeline[142] <= delay_pipeline[141];
          delay_pipeline[143] <= delay_pipeline[142];
          delay_pipeline[144] <= delay_pipeline[143];
          delay_pipeline[145] <= delay_pipeline[144];
          delay_pipeline[146] <= delay_pipeline[145];
          delay_pipeline[147] <= delay_pipeline[146];
          delay_pipeline[148] <= delay_pipeline[147];
          delay_pipeline[149] <= delay_pipeline[148];
          delay_pipeline[150] <= delay_pipeline[149];
          delay_pipeline[151] <= delay_pipeline[150];
          delay_pipeline[152] <= delay_pipeline[151];
          delay_pipeline[153] <= delay_pipeline[152];
          delay_pipeline[154] <= delay_pipeline[153];
          delay_pipeline[155] <= delay_pipeline[154];
          delay_pipeline[156] <= delay_pipeline[155];
          delay_pipeline[157] <= delay_pipeline[156];
          delay_pipeline[158] <= delay_pipeline[157];
          delay_pipeline[159] <= delay_pipeline[158];
          delay_pipeline[160] <= delay_pipeline[159];
          delay_pipeline[161] <= delay_pipeline[160];
          delay_pipeline[162] <= delay_pipeline[161];
          delay_pipeline[163] <= delay_pipeline[162];
          delay_pipeline[164] <= delay_pipeline[163];
          delay_pipeline[165] <= delay_pipeline[164];
          delay_pipeline[166] <= delay_pipeline[165];
          delay_pipeline[167] <= delay_pipeline[166];
          delay_pipeline[168] <= delay_pipeline[167];
          delay_pipeline[169] <= delay_pipeline[168];
          delay_pipeline[170] <= delay_pipeline[169];
          delay_pipeline[171] <= delay_pipeline[170];
          delay_pipeline[172] <= delay_pipeline[171];
          delay_pipeline[173] <= delay_pipeline[172];
          delay_pipeline[174] <= delay_pipeline[173];
          delay_pipeline[175] <= delay_pipeline[174];
          delay_pipeline[176] <= delay_pipeline[175];
          delay_pipeline[177] <= delay_pipeline[176];
          delay_pipeline[178] <= delay_pipeline[177];
          delay_pipeline[179] <= delay_pipeline[178];
          delay_pipeline[180] <= delay_pipeline[179];
          delay_pipeline[181] <= delay_pipeline[180];
          delay_pipeline[182] <= delay_pipeline[181];
          delay_pipeline[183] <= delay_pipeline[182];
          delay_pipeline[184] <= delay_pipeline[183];
          delay_pipeline[185] <= delay_pipeline[184];
          delay_pipeline[186] <= delay_pipeline[185];
          delay_pipeline[187] <= delay_pipeline[186];
          delay_pipeline[188] <= delay_pipeline[187];
          delay_pipeline[189] <= delay_pipeline[188];
          delay_pipeline[190] <= delay_pipeline[189];
          delay_pipeline[191] <= delay_pipeline[190];
          delay_pipeline[192] <= delay_pipeline[191];
          delay_pipeline[193] <= delay_pipeline[192];
          delay_pipeline[194] <= delay_pipeline[193];
          delay_pipeline[195] <= delay_pipeline[194];
          delay_pipeline[196] <= delay_pipeline[195];
          delay_pipeline[197] <= delay_pipeline[196];
          delay_pipeline[198] <= delay_pipeline[197];
          delay_pipeline[199] <= delay_pipeline[198];
          delay_pipeline[200] <= delay_pipeline[199];
          delay_pipeline[201] <= delay_pipeline[200];
          delay_pipeline[202] <= delay_pipeline[201];
          delay_pipeline[203] <= delay_pipeline[202];
          delay_pipeline[204] <= delay_pipeline[203];
          delay_pipeline[205] <= delay_pipeline[204];
          delay_pipeline[206] <= delay_pipeline[205];
          delay_pipeline[207] <= delay_pipeline[206];
          delay_pipeline[208] <= delay_pipeline[207];
          delay_pipeline[209] <= delay_pipeline[208];
          delay_pipeline[210] <= delay_pipeline[209];
          delay_pipeline[211] <= delay_pipeline[210];
          delay_pipeline[212] <= delay_pipeline[211];
          delay_pipeline[213] <= delay_pipeline[212];
          delay_pipeline[214] <= delay_pipeline[213];
          delay_pipeline[215] <= delay_pipeline[214];
          delay_pipeline[216] <= delay_pipeline[215];
          delay_pipeline[217] <= delay_pipeline[216];
          delay_pipeline[218] <= delay_pipeline[217];
          delay_pipeline[219] <= delay_pipeline[218];
          delay_pipeline[220] <= delay_pipeline[219];
          delay_pipeline[221] <= delay_pipeline[220];
          delay_pipeline[222] <= delay_pipeline[221];
          delay_pipeline[223] <= delay_pipeline[222];
          delay_pipeline[224] <= delay_pipeline[223];
          delay_pipeline[225] <= delay_pipeline[224];
          delay_pipeline[226] <= delay_pipeline[225];
          delay_pipeline[227] <= delay_pipeline[226];
          delay_pipeline[228] <= delay_pipeline[227];
          delay_pipeline[229] <= delay_pipeline[228];
          delay_pipeline[230] <= delay_pipeline[229];
          delay_pipeline[231] <= delay_pipeline[230];
          delay_pipeline[232] <= delay_pipeline[231];
          delay_pipeline[233] <= delay_pipeline[232];
          delay_pipeline[234] <= delay_pipeline[233];
          delay_pipeline[235] <= delay_pipeline[234];
          delay_pipeline[236] <= delay_pipeline[235];
          delay_pipeline[237] <= delay_pipeline[236];
          delay_pipeline[238] <= delay_pipeline[237];
          delay_pipeline[239] <= delay_pipeline[238];
          delay_pipeline[240] <= delay_pipeline[239];
          delay_pipeline[241] <= delay_pipeline[240];
          delay_pipeline[242] <= delay_pipeline[241];
          delay_pipeline[243] <= delay_pipeline[242];
          delay_pipeline[244] <= delay_pipeline[243];
          delay_pipeline[245] <= delay_pipeline[244];
          delay_pipeline[246] <= delay_pipeline[245];
          delay_pipeline[247] <= delay_pipeline[246];
          delay_pipeline[248] <= delay_pipeline[247];
          delay_pipeline[249] <= delay_pipeline[248];
          delay_pipeline[250] <= delay_pipeline[249];
          delay_pipeline[251] <= delay_pipeline[250];
          delay_pipeline[252] <= delay_pipeline[251];
          delay_pipeline[253] <= delay_pipeline[252];
          delay_pipeline[254] <= delay_pipeline[253];
          delay_pipeline[255] <= delay_pipeline[254];
          delay_pipeline[256] <= delay_pipeline[255];
          delay_pipeline[257] <= delay_pipeline[256];
          delay_pipeline[258] <= delay_pipeline[257];
          delay_pipeline[259] <= delay_pipeline[258];
          delay_pipeline[260] <= delay_pipeline[259];
          delay_pipeline[261] <= delay_pipeline[260];
          delay_pipeline[262] <= delay_pipeline[261];
          delay_pipeline[263] <= delay_pipeline[262];
          delay_pipeline[264] <= delay_pipeline[263];
          delay_pipeline[265] <= delay_pipeline[264];
          delay_pipeline[266] <= delay_pipeline[265];
          delay_pipeline[267] <= delay_pipeline[266];
          delay_pipeline[268] <= delay_pipeline[267];
          delay_pipeline[269] <= delay_pipeline[268];
          delay_pipeline[270] <= delay_pipeline[269];
          delay_pipeline[271] <= delay_pipeline[270];
          delay_pipeline[272] <= delay_pipeline[271];
          delay_pipeline[273] <= delay_pipeline[272];
          delay_pipeline[274] <= delay_pipeline[273];
          delay_pipeline[275] <= delay_pipeline[274];
          delay_pipeline[276] <= delay_pipeline[275];
          delay_pipeline[277] <= delay_pipeline[276];
          delay_pipeline[278] <= delay_pipeline[277];
          delay_pipeline[279] <= delay_pipeline[278];
          delay_pipeline[280] <= delay_pipeline[279];
          delay_pipeline[281] <= delay_pipeline[280];
          delay_pipeline[282] <= delay_pipeline[281];
          delay_pipeline[283] <= delay_pipeline[282];
          delay_pipeline[284] <= delay_pipeline[283];
          delay_pipeline[285] <= delay_pipeline[284];
          delay_pipeline[286] <= delay_pipeline[285];
          delay_pipeline[287] <= delay_pipeline[286];
          delay_pipeline[288] <= delay_pipeline[287];
          delay_pipeline[289] <= delay_pipeline[288];
          delay_pipeline[290] <= delay_pipeline[289];
          delay_pipeline[291] <= delay_pipeline[290];
          delay_pipeline[292] <= delay_pipeline[291];
          delay_pipeline[293] <= delay_pipeline[292];
          delay_pipeline[294] <= delay_pipeline[293];
          delay_pipeline[295] <= delay_pipeline[294];
          delay_pipeline[296] <= delay_pipeline[295];
          delay_pipeline[297] <= delay_pipeline[296];
          delay_pipeline[298] <= delay_pipeline[297];
          delay_pipeline[299] <= delay_pipeline[298];
          delay_pipeline[300] <= delay_pipeline[299];
          delay_pipeline[301] <= delay_pipeline[300];
          delay_pipeline[302] <= delay_pipeline[301];
          delay_pipeline[303] <= delay_pipeline[302];
          delay_pipeline[304] <= delay_pipeline[303];
          delay_pipeline[305] <= delay_pipeline[304];
          delay_pipeline[306] <= delay_pipeline[305];
          delay_pipeline[307] <= delay_pipeline[306];
          delay_pipeline[308] <= delay_pipeline[307];
          delay_pipeline[309] <= delay_pipeline[308];
          delay_pipeline[310] <= delay_pipeline[309];
          delay_pipeline[311] <= delay_pipeline[310];
          delay_pipeline[312] <= delay_pipeline[311];
          delay_pipeline[313] <= delay_pipeline[312];
          delay_pipeline[314] <= delay_pipeline[313];
          delay_pipeline[315] <= delay_pipeline[314];
          delay_pipeline[316] <= delay_pipeline[315];
          delay_pipeline[317] <= delay_pipeline[316];
          delay_pipeline[318] <= delay_pipeline[317];
          delay_pipeline[319] <= delay_pipeline[318];
          delay_pipeline[320] <= delay_pipeline[319];
          delay_pipeline[321] <= delay_pipeline[320];
          delay_pipeline[322] <= delay_pipeline[321];
          delay_pipeline[323] <= delay_pipeline[322];
          delay_pipeline[324] <= delay_pipeline[323];
          delay_pipeline[325] <= delay_pipeline[324];
          delay_pipeline[326] <= delay_pipeline[325];
          delay_pipeline[327] <= delay_pipeline[326];
          delay_pipeline[328] <= delay_pipeline[327];
          delay_pipeline[329] <= delay_pipeline[328];
          delay_pipeline[330] <= delay_pipeline[329];
          delay_pipeline[331] <= delay_pipeline[330];
          delay_pipeline[332] <= delay_pipeline[331];
          delay_pipeline[333] <= delay_pipeline[332];
          delay_pipeline[334] <= delay_pipeline[333];
          delay_pipeline[335] <= delay_pipeline[334];
          delay_pipeline[336] <= delay_pipeline[335];
          delay_pipeline[337] <= delay_pipeline[336];
          delay_pipeline[338] <= delay_pipeline[337];
          delay_pipeline[339] <= delay_pipeline[338];
          delay_pipeline[340] <= delay_pipeline[339];
          delay_pipeline[341] <= delay_pipeline[340];
          delay_pipeline[342] <= delay_pipeline[341];
          delay_pipeline[343] <= delay_pipeline[342];
          delay_pipeline[344] <= delay_pipeline[343];
          delay_pipeline[345] <= delay_pipeline[344];
          delay_pipeline[346] <= delay_pipeline[345];
          delay_pipeline[347] <= delay_pipeline[346];
          delay_pipeline[348] <= delay_pipeline[347];
          delay_pipeline[349] <= delay_pipeline[348];
          delay_pipeline[350] <= delay_pipeline[349];
          delay_pipeline[351] <= delay_pipeline[350];
          delay_pipeline[352] <= delay_pipeline[351];
          delay_pipeline[353] <= delay_pipeline[352];
          delay_pipeline[354] <= delay_pipeline[353];
          delay_pipeline[355] <= delay_pipeline[354];
          delay_pipeline[356] <= delay_pipeline[355];
          delay_pipeline[357] <= delay_pipeline[356];
          delay_pipeline[358] <= delay_pipeline[357];
          delay_pipeline[359] <= delay_pipeline[358];
          delay_pipeline[360] <= delay_pipeline[359];
          delay_pipeline[361] <= delay_pipeline[360];
          delay_pipeline[362] <= delay_pipeline[361];
          delay_pipeline[363] <= delay_pipeline[362];
          delay_pipeline[364] <= delay_pipeline[363];
          delay_pipeline[365] <= delay_pipeline[364];
          delay_pipeline[366] <= delay_pipeline[365];
          delay_pipeline[367] <= delay_pipeline[366];
          delay_pipeline[368] <= delay_pipeline[367];
          delay_pipeline[369] <= delay_pipeline[368];
          delay_pipeline[370] <= delay_pipeline[369];
          delay_pipeline[371] <= delay_pipeline[370];
          delay_pipeline[372] <= delay_pipeline[371];
          delay_pipeline[373] <= delay_pipeline[372];
          delay_pipeline[374] <= delay_pipeline[373];
          delay_pipeline[375] <= delay_pipeline[374];
          delay_pipeline[376] <= delay_pipeline[375];
          delay_pipeline[377] <= delay_pipeline[376];
          delay_pipeline[378] <= delay_pipeline[377];
          delay_pipeline[379] <= delay_pipeline[378];
          delay_pipeline[380] <= delay_pipeline[379];
          delay_pipeline[381] <= delay_pipeline[380];
          delay_pipeline[382] <= delay_pipeline[381];
          delay_pipeline[383] <= delay_pipeline[382];
          delay_pipeline[384] <= delay_pipeline[383];
          delay_pipeline[385] <= delay_pipeline[384];
          delay_pipeline[386] <= delay_pipeline[385];
          delay_pipeline[387] <= delay_pipeline[386];
          delay_pipeline[388] <= delay_pipeline[387];
          delay_pipeline[389] <= delay_pipeline[388];
          delay_pipeline[390] <= delay_pipeline[389];
          delay_pipeline[391] <= delay_pipeline[390];
          delay_pipeline[392] <= delay_pipeline[391];
          delay_pipeline[393] <= delay_pipeline[392];
          delay_pipeline[394] <= delay_pipeline[393];
          delay_pipeline[395] <= delay_pipeline[394];
          delay_pipeline[396] <= delay_pipeline[395];
          delay_pipeline[397] <= delay_pipeline[396];
          delay_pipeline[398] <= delay_pipeline[397];
          delay_pipeline[399] <= delay_pipeline[398];
          delay_pipeline[400] <= delay_pipeline[399];
          delay_pipeline[401] <= delay_pipeline[400];
          delay_pipeline[402] <= delay_pipeline[401];
          delay_pipeline[403] <= delay_pipeline[402];
          delay_pipeline[404] <= delay_pipeline[403];
          delay_pipeline[405] <= delay_pipeline[404];
          delay_pipeline[406] <= delay_pipeline[405];
          delay_pipeline[407] <= delay_pipeline[406];
          delay_pipeline[408] <= delay_pipeline[407];
          delay_pipeline[409] <= delay_pipeline[408];
          delay_pipeline[410] <= delay_pipeline[409];
          delay_pipeline[411] <= delay_pipeline[410];
          delay_pipeline[412] <= delay_pipeline[411];
          delay_pipeline[413] <= delay_pipeline[412];
          delay_pipeline[414] <= delay_pipeline[413];
          delay_pipeline[415] <= delay_pipeline[414];
          delay_pipeline[416] <= delay_pipeline[415];
          delay_pipeline[417] <= delay_pipeline[416];
          delay_pipeline[418] <= delay_pipeline[417];
          delay_pipeline[419] <= delay_pipeline[418];
          delay_pipeline[420] <= delay_pipeline[419];
          delay_pipeline[421] <= delay_pipeline[420];
          delay_pipeline[422] <= delay_pipeline[421];
          delay_pipeline[423] <= delay_pipeline[422];
          delay_pipeline[424] <= delay_pipeline[423];
          delay_pipeline[425] <= delay_pipeline[424];
          delay_pipeline[426] <= delay_pipeline[425];
          delay_pipeline[427] <= delay_pipeline[426];
          delay_pipeline[428] <= delay_pipeline[427];
          delay_pipeline[429] <= delay_pipeline[428];
          delay_pipeline[430] <= delay_pipeline[429];
          delay_pipeline[431] <= delay_pipeline[430];
          delay_pipeline[432] <= delay_pipeline[431];
          delay_pipeline[433] <= delay_pipeline[432];
          delay_pipeline[434] <= delay_pipeline[433];
          delay_pipeline[435] <= delay_pipeline[434];
          delay_pipeline[436] <= delay_pipeline[435];
          delay_pipeline[437] <= delay_pipeline[436];
          delay_pipeline[438] <= delay_pipeline[437];
          delay_pipeline[439] <= delay_pipeline[438];
          delay_pipeline[440] <= delay_pipeline[439];
          delay_pipeline[441] <= delay_pipeline[440];
          delay_pipeline[442] <= delay_pipeline[441];
          delay_pipeline[443] <= delay_pipeline[442];
          delay_pipeline[444] <= delay_pipeline[443];
          delay_pipeline[445] <= delay_pipeline[444];
          delay_pipeline[446] <= delay_pipeline[445];
          delay_pipeline[447] <= delay_pipeline[446];
          delay_pipeline[448] <= delay_pipeline[447];
          delay_pipeline[449] <= delay_pipeline[448];
          delay_pipeline[450] <= delay_pipeline[449];
          delay_pipeline[451] <= delay_pipeline[450];
          delay_pipeline[452] <= delay_pipeline[451];
          delay_pipeline[453] <= delay_pipeline[452];
          delay_pipeline[454] <= delay_pipeline[453];
          delay_pipeline[455] <= delay_pipeline[454];
          delay_pipeline[456] <= delay_pipeline[455];
          delay_pipeline[457] <= delay_pipeline[456];
          delay_pipeline[458] <= delay_pipeline[457];
          delay_pipeline[459] <= delay_pipeline[458];
          delay_pipeline[460] <= delay_pipeline[459];
          delay_pipeline[461] <= delay_pipeline[460];
          delay_pipeline[462] <= delay_pipeline[461];
          delay_pipeline[463] <= delay_pipeline[462];
          delay_pipeline[464] <= delay_pipeline[463];
          delay_pipeline[465] <= delay_pipeline[464];
          delay_pipeline[466] <= delay_pipeline[465];
          delay_pipeline[467] <= delay_pipeline[466];
          delay_pipeline[468] <= delay_pipeline[467];
          delay_pipeline[469] <= delay_pipeline[468];
          delay_pipeline[470] <= delay_pipeline[469];
          delay_pipeline[471] <= delay_pipeline[470];
          delay_pipeline[472] <= delay_pipeline[471];
          delay_pipeline[473] <= delay_pipeline[472];
          delay_pipeline[474] <= delay_pipeline[473];
          delay_pipeline[475] <= delay_pipeline[474];
          delay_pipeline[476] <= delay_pipeline[475];
          delay_pipeline[477] <= delay_pipeline[476];
          delay_pipeline[478] <= delay_pipeline[477];
          delay_pipeline[479] <= delay_pipeline[478];
          delay_pipeline[480] <= delay_pipeline[479];
          delay_pipeline[481] <= delay_pipeline[480];
          delay_pipeline[482] <= delay_pipeline[481];
          delay_pipeline[483] <= delay_pipeline[482];
          delay_pipeline[484] <= delay_pipeline[483];
          delay_pipeline[485] <= delay_pipeline[484];
          delay_pipeline[486] <= delay_pipeline[485];
          delay_pipeline[487] <= delay_pipeline[486];
          delay_pipeline[488] <= delay_pipeline[487];
          delay_pipeline[489] <= delay_pipeline[488];
          delay_pipeline[490] <= delay_pipeline[489];
          delay_pipeline[491] <= delay_pipeline[490];
          delay_pipeline[492] <= delay_pipeline[491];
          delay_pipeline[493] <= delay_pipeline[492];
          delay_pipeline[494] <= delay_pipeline[493];
          delay_pipeline[495] <= delay_pipeline[494];
          delay_pipeline[496] <= delay_pipeline[495];
          delay_pipeline[497] <= delay_pipeline[496];
          delay_pipeline[498] <= delay_pipeline[497];
          delay_pipeline[499] <= delay_pipeline[498];
          delay_pipeline[500] <= delay_pipeline[499];
          delay_pipeline[501] <= delay_pipeline[500];
          delay_pipeline[502] <= delay_pipeline[501];
          delay_pipeline[503] <= delay_pipeline[502];
          delay_pipeline[504] <= delay_pipeline[503];
          delay_pipeline[505] <= delay_pipeline[504];
          delay_pipeline[506] <= delay_pipeline[505];
          delay_pipeline[507] <= delay_pipeline[506];
          delay_pipeline[508] <= delay_pipeline[507];
          delay_pipeline[509] <= delay_pipeline[508];
          delay_pipeline[510] <= delay_pipeline[509];
          delay_pipeline[511] <= delay_pipeline[510];
          delay_pipeline[512] <= delay_pipeline[511];
          delay_pipeline[513] <= delay_pipeline[512];
          delay_pipeline[514] <= delay_pipeline[513];
          delay_pipeline[515] <= delay_pipeline[514];
          delay_pipeline[516] <= delay_pipeline[515];
          delay_pipeline[517] <= delay_pipeline[516];
          delay_pipeline[518] <= delay_pipeline[517];
          delay_pipeline[519] <= delay_pipeline[518];
          delay_pipeline[520] <= delay_pipeline[519];
          delay_pipeline[521] <= delay_pipeline[520];
          delay_pipeline[522] <= delay_pipeline[521];
          delay_pipeline[523] <= delay_pipeline[522];
          delay_pipeline[524] <= delay_pipeline[523];
          delay_pipeline[525] <= delay_pipeline[524];
          delay_pipeline[526] <= delay_pipeline[525];
          delay_pipeline[527] <= delay_pipeline[526];
          delay_pipeline[528] <= delay_pipeline[527];
          delay_pipeline[529] <= delay_pipeline[528];
          delay_pipeline[530] <= delay_pipeline[529];
          delay_pipeline[531] <= delay_pipeline[530];
          delay_pipeline[532] <= delay_pipeline[531];
          delay_pipeline[533] <= delay_pipeline[532];
          delay_pipeline[534] <= delay_pipeline[533];
          delay_pipeline[535] <= delay_pipeline[534];
          delay_pipeline[536] <= delay_pipeline[535];
          delay_pipeline[537] <= delay_pipeline[536];
          delay_pipeline[538] <= delay_pipeline[537];
          delay_pipeline[539] <= delay_pipeline[538];
          delay_pipeline[540] <= delay_pipeline[539];
          delay_pipeline[541] <= delay_pipeline[540];
          delay_pipeline[542] <= delay_pipeline[541];
          delay_pipeline[543] <= delay_pipeline[542];
          delay_pipeline[544] <= delay_pipeline[543];
          delay_pipeline[545] <= delay_pipeline[544];
          delay_pipeline[546] <= delay_pipeline[545];
          delay_pipeline[547] <= delay_pipeline[546];
          delay_pipeline[548] <= delay_pipeline[547];
          delay_pipeline[549] <= delay_pipeline[548];
          delay_pipeline[550] <= delay_pipeline[549];
          delay_pipeline[551] <= delay_pipeline[550];
          delay_pipeline[552] <= delay_pipeline[551];
          delay_pipeline[553] <= delay_pipeline[552];
          delay_pipeline[554] <= delay_pipeline[553];
          delay_pipeline[555] <= delay_pipeline[554];
          delay_pipeline[556] <= delay_pipeline[555];
          delay_pipeline[557] <= delay_pipeline[556];
          delay_pipeline[558] <= delay_pipeline[557];
          delay_pipeline[559] <= delay_pipeline[558];
          delay_pipeline[560] <= delay_pipeline[559];
          delay_pipeline[561] <= delay_pipeline[560];
          delay_pipeline[562] <= delay_pipeline[561];
          delay_pipeline[563] <= delay_pipeline[562];
          delay_pipeline[564] <= delay_pipeline[563];
          delay_pipeline[565] <= delay_pipeline[564];
          delay_pipeline[566] <= delay_pipeline[565];
          delay_pipeline[567] <= delay_pipeline[566];
          delay_pipeline[568] <= delay_pipeline[567];
          delay_pipeline[569] <= delay_pipeline[568];
          delay_pipeline[570] <= delay_pipeline[569];
          delay_pipeline[571] <= delay_pipeline[570];
          delay_pipeline[572] <= delay_pipeline[571];
          delay_pipeline[573] <= delay_pipeline[572];
          delay_pipeline[574] <= delay_pipeline[573];
          delay_pipeline[575] <= delay_pipeline[574];
          delay_pipeline[576] <= delay_pipeline[575];
          delay_pipeline[577] <= delay_pipeline[576];
          delay_pipeline[578] <= delay_pipeline[577];
          delay_pipeline[579] <= delay_pipeline[578];
          delay_pipeline[580] <= delay_pipeline[579];
          delay_pipeline[581] <= delay_pipeline[580];
          delay_pipeline[582] <= delay_pipeline[581];
          delay_pipeline[583] <= delay_pipeline[582];
          delay_pipeline[584] <= delay_pipeline[583];
          delay_pipeline[585] <= delay_pipeline[584];
          delay_pipeline[586] <= delay_pipeline[585];
          delay_pipeline[587] <= delay_pipeline[586];
          delay_pipeline[588] <= delay_pipeline[587];
          delay_pipeline[589] <= delay_pipeline[588];
          delay_pipeline[590] <= delay_pipeline[589];
          delay_pipeline[591] <= delay_pipeline[590];
          delay_pipeline[592] <= delay_pipeline[591];
          delay_pipeline[593] <= delay_pipeline[592];
          delay_pipeline[594] <= delay_pipeline[593];
          delay_pipeline[595] <= delay_pipeline[594];
          delay_pipeline[596] <= delay_pipeline[595];
          delay_pipeline[597] <= delay_pipeline[596];
          delay_pipeline[598] <= delay_pipeline[597];
          delay_pipeline[599] <= delay_pipeline[598];
          delay_pipeline[600] <= delay_pipeline[599];
          delay_pipeline[601] <= delay_pipeline[600];
          delay_pipeline[602] <= delay_pipeline[601];
          delay_pipeline[603] <= delay_pipeline[602];
          delay_pipeline[604] <= delay_pipeline[603];
          delay_pipeline[605] <= delay_pipeline[604];
          delay_pipeline[606] <= delay_pipeline[605];
          delay_pipeline[607] <= delay_pipeline[606];
          delay_pipeline[608] <= delay_pipeline[607];
          delay_pipeline[609] <= delay_pipeline[608];
          delay_pipeline[610] <= delay_pipeline[609];
          delay_pipeline[611] <= delay_pipeline[610];
          delay_pipeline[612] <= delay_pipeline[611];
          delay_pipeline[613] <= delay_pipeline[612];
          delay_pipeline[614] <= delay_pipeline[613];
          delay_pipeline[615] <= delay_pipeline[614];
          delay_pipeline[616] <= delay_pipeline[615];
          delay_pipeline[617] <= delay_pipeline[616];
          delay_pipeline[618] <= delay_pipeline[617];
          delay_pipeline[619] <= delay_pipeline[618];
          delay_pipeline[620] <= delay_pipeline[619];
          delay_pipeline[621] <= delay_pipeline[620];
          delay_pipeline[622] <= delay_pipeline[621];
          delay_pipeline[623] <= delay_pipeline[622];
          delay_pipeline[624] <= delay_pipeline[623];
          delay_pipeline[625] <= delay_pipeline[624];
          delay_pipeline[626] <= delay_pipeline[625];
          delay_pipeline[627] <= delay_pipeline[626];
          delay_pipeline[628] <= delay_pipeline[627];
          delay_pipeline[629] <= delay_pipeline[628];
          delay_pipeline[630] <= delay_pipeline[629];
          delay_pipeline[631] <= delay_pipeline[630];
          delay_pipeline[632] <= delay_pipeline[631];
          delay_pipeline[633] <= delay_pipeline[632];
          delay_pipeline[634] <= delay_pipeline[633];
          delay_pipeline[635] <= delay_pipeline[634];
          delay_pipeline[636] <= delay_pipeline[635];
          delay_pipeline[637] <= delay_pipeline[636];
          delay_pipeline[638] <= delay_pipeline[637];
          delay_pipeline[639] <= delay_pipeline[638];
        end
      end
    end // Delay_Pipeline_1_process


  assign mem_addr_1 = {delay_pipeline[159], delay_pipeline[127], delay_pipeline[95], delay_pipeline[63], delay_pipeline[31], serialoutb1};

  always @(mem_addr_1)
  begin
    case(mem_addr_1)
      6'b000000 : memoutb1_1 = 30'b000000000000000000000000000000;
      6'b000001 : memoutb1_1 = 30'b000000000001100101001100110010;
      6'b000010 : memoutb1_1 = 30'b000000001110000011110110010000;
      6'b000011 : memoutb1_1 = 30'b000000001111101001000011000010;
      6'b000100 : memoutb1_1 = 30'b000000111111110001110101101110;
      6'b000101 : memoutb1_1 = 30'b000001000001010111000010100000;
      6'b000110 : memoutb1_1 = 30'b000001001101110101101011111110;
      6'b000111 : memoutb1_1 = 30'b000001001111011010111000110000;
      6'b001000 : memoutb1_1 = 30'b000011001001111101111111110010;
      6'b001001 : memoutb1_1 = 30'b000011001011100011001100100100;
      6'b001010 : memoutb1_1 = 30'b000011011000000001110110000010;
      6'b001011 : memoutb1_1 = 30'b000011011001100111000010110100;
      6'b001100 : memoutb1_1 = 30'b000100001001101111110101100000;
      6'b001101 : memoutb1_1 = 30'b000100001011010101000010010010;
      6'b001110 : memoutb1_1 = 30'b000100010111110011101011110000;
      6'b001111 : memoutb1_1 = 30'b000100011001011000111000100010;
      6'b010000 : memoutb1_1 = 30'b000111110011010000101011001011;
      6'b010001 : memoutb1_1 = 30'b000111110100110101110111111101;
      6'b010010 : memoutb1_1 = 30'b001000000001010100100001011011;
      6'b010011 : memoutb1_1 = 30'b001000000010111001101110001101;
      6'b010100 : memoutb1_1 = 30'b001000110011000010100000111001;
      6'b010101 : memoutb1_1 = 30'b001000110100100111101101101011;
      6'b010110 : memoutb1_1 = 30'b001001000001000110010111001001;
      6'b010111 : memoutb1_1 = 30'b001001000010101011100011111011;
      6'b011000 : memoutb1_1 = 30'b001010111101001110101010111101;
      6'b011001 : memoutb1_1 = 30'b001010111110110011110111101111;
      6'b011010 : memoutb1_1 = 30'b001011001011010010100001001101;
      6'b011011 : memoutb1_1 = 30'b001011001100110111101101111111;
      6'b011100 : memoutb1_1 = 30'b001011111101000000100000101011;
      6'b011101 : memoutb1_1 = 30'b001011111110100101101101011101;
      6'b011110 : memoutb1_1 = 30'b001100001011000100010110111011;
      6'b011111 : memoutb1_1 = 30'b001100001100101001100011101101;
      6'b100000 : memoutb1_1 = 30'b001111111011000001100010111011;
      6'b100001 : memoutb1_1 = 30'b001111111100100110101111101101;
      6'b100010 : memoutb1_1 = 30'b010000001001000101011001001011;
      6'b100011 : memoutb1_1 = 30'b010000001010101010100101111101;
      6'b100100 : memoutb1_1 = 30'b010000111010110011011000101001;
      6'b100101 : memoutb1_1 = 30'b010000111100011000100101011011;
      6'b100110 : memoutb1_1 = 30'b010001001000110111001110111001;
      6'b100111 : memoutb1_1 = 30'b010001001010011100011011101011;
      6'b101000 : memoutb1_1 = 30'b010011000100111111100010101101;
      6'b101001 : memoutb1_1 = 30'b010011000110100100101111011111;
      6'b101010 : memoutb1_1 = 30'b010011010011000011011000111101;
      6'b101011 : memoutb1_1 = 30'b010011010100101000100101101111;
      6'b101100 : memoutb1_1 = 30'b010100000100110001011000011011;
      6'b101101 : memoutb1_1 = 30'b010100000110010110100101001101;
      6'b101110 : memoutb1_1 = 30'b010100010010110101001110101011;
      6'b101111 : memoutb1_1 = 30'b010100010100011010011011011101;
      6'b110000 : memoutb1_1 = 30'b010111101110010010001110000110;
      6'b110001 : memoutb1_1 = 30'b010111101111110111011010111000;
      6'b110010 : memoutb1_1 = 30'b010111111100010110000100010110;
      6'b110011 : memoutb1_1 = 30'b010111111101111011010001001000;
      6'b110100 : memoutb1_1 = 30'b011000101110000100000011110100;
      6'b110101 : memoutb1_1 = 30'b011000101111101001010000100110;
      6'b110110 : memoutb1_1 = 30'b011000111100000111111010000100;
      6'b110111 : memoutb1_1 = 30'b011000111101101101000110110110;
      6'b111000 : memoutb1_1 = 30'b011010111000010000001101111000;
      6'b111001 : memoutb1_1 = 30'b011010111001110101011010101010;
      6'b111010 : memoutb1_1 = 30'b011011000110010100000100001000;
      6'b111011 : memoutb1_1 = 30'b011011000111111001010000111010;
      6'b111100 : memoutb1_1 = 30'b011011111000000010000011100110;
      6'b111101 : memoutb1_1 = 30'b011011111001100111010000011000;
      6'b111110 : memoutb1_1 = 30'b011100000110000101111001110110;
      6'b111111 : memoutb1_1 = 30'b011100000111101011000110101000;
      default : memoutb1_1 = 30'b011100000111101011000110101000;
    endcase
  end

  assign mem_addr_2 = {delay_pipeline[351], delay_pipeline[319], delay_pipeline[287], delay_pipeline[255], delay_pipeline[223], delay_pipeline[191]};

  always @(mem_addr_2)
  begin
    case(mem_addr_2)
      6'b000000 : memoutb1_2 = 34'b0000000000000000000000000000000000;
      6'b000001 : memoutb1_2 = 34'b0000011011101101110001110110000010;
      6'b000010 : memoutb1_2 = 34'b0000101001111110100000110010000101;
      6'b000011 : memoutb1_2 = 34'b0001000101101100010010101000000111;
      6'b000100 : memoutb1_2 = 34'b0000111000000001111100110001111100;
      6'b000101 : memoutb1_2 = 34'b0001010011101111101110100111111110;
      6'b000110 : memoutb1_2 = 34'b0001100010000000011101100100000001;
      6'b000111 : memoutb1_2 = 34'b0001111101101110001111011010000011;
      6'b001000 : memoutb1_2 = 34'b0001000010011100000001011101010001;
      6'b001001 : memoutb1_2 = 34'b0001011110001001110011010011010011;
      6'b001010 : memoutb1_2 = 34'b0001101100011010100010001111010110;
      6'b001011 : memoutb1_2 = 34'b0010001000001000010100000101011000;
      6'b001100 : memoutb1_2 = 34'b0001111010011101111110001111001101;
      6'b001101 : memoutb1_2 = 34'b0010010110001011110000000101001111;
      6'b001110 : memoutb1_2 = 34'b0010100100011100011111000001010010;
      6'b001111 : memoutb1_2 = 34'b0011000000001010010000110111010100;
      6'b010000 : memoutb1_2 = 34'b0001000110010010011001010111001101;
      6'b010001 : memoutb1_2 = 34'b0001100010000000001011001101001111;
      6'b010010 : memoutb1_2 = 34'b0001110000010000111010001001010010;
      6'b010011 : memoutb1_2 = 34'b0010001011111110101011111111010100;
      6'b010100 : memoutb1_2 = 34'b0001111110010100010110001001001001;
      6'b010101 : memoutb1_2 = 34'b0010011010000010000111111111001011;
      6'b010110 : memoutb1_2 = 34'b0010101000010010110110111011001110;
      6'b010111 : memoutb1_2 = 34'b0011000100000000101000110001010000;
      6'b011000 : memoutb1_2 = 34'b0010001000101110011010110100011110;
      6'b011001 : memoutb1_2 = 34'b0010100100011100001100101010100000;
      6'b011010 : memoutb1_2 = 34'b0010110010101100111011100110100011;
      6'b011011 : memoutb1_2 = 34'b0011001110011010101101011100100101;
      6'b011100 : memoutb1_2 = 34'b0011000000110000010111100110011010;
      6'b011101 : memoutb1_2 = 34'b0011011100011110001001011100011100;
      6'b011110 : memoutb1_2 = 34'b0011101010101110111000011000011111;
      6'b011111 : memoutb1_2 = 34'b0100000110011100101010001110100001;
      6'b100000 : memoutb1_2 = 34'b0001000010011100000001011101010001;
      6'b100001 : memoutb1_2 = 34'b0001011110001001110011010011010011;
      6'b100010 : memoutb1_2 = 34'b0001101100011010100010001111010110;
      6'b100011 : memoutb1_2 = 34'b0010001000001000010100000101011000;
      6'b100100 : memoutb1_2 = 34'b0001111010011101111110001111001101;
      6'b100101 : memoutb1_2 = 34'b0010010110001011110000000101001111;
      6'b100110 : memoutb1_2 = 34'b0010100100011100011111000001010010;
      6'b100111 : memoutb1_2 = 34'b0011000000001010010000110111010100;
      6'b101000 : memoutb1_2 = 34'b0010000100111000000010111010100010;
      6'b101001 : memoutb1_2 = 34'b0010100000100101110100110000100100;
      6'b101010 : memoutb1_2 = 34'b0010101110110110100011101100100111;
      6'b101011 : memoutb1_2 = 34'b0011001010100100010101100010101001;
      6'b101100 : memoutb1_2 = 34'b0010111100111001111111101100011110;
      6'b101101 : memoutb1_2 = 34'b0011011000100111110001100010100000;
      6'b101110 : memoutb1_2 = 34'b0011100110111000100000011110100011;
      6'b101111 : memoutb1_2 = 34'b0100000010100110010010010100100101;
      6'b110000 : memoutb1_2 = 34'b0010001000101110011010110100011110;
      6'b110001 : memoutb1_2 = 34'b0010100100011100001100101010100000;
      6'b110010 : memoutb1_2 = 34'b0010110010101100111011100110100011;
      6'b110011 : memoutb1_2 = 34'b0011001110011010101101011100100101;
      6'b110100 : memoutb1_2 = 34'b0011000000110000010111100110011010;
      6'b110101 : memoutb1_2 = 34'b0011011100011110001001011100011100;
      6'b110110 : memoutb1_2 = 34'b0011101010101110111000011000011111;
      6'b110111 : memoutb1_2 = 34'b0100000110011100101010001110100001;
      6'b111000 : memoutb1_2 = 34'b0011001011001010011100010001101111;
      6'b111001 : memoutb1_2 = 34'b0011100110111000001110000111110001;
      6'b111010 : memoutb1_2 = 34'b0011110101001000111101000011110100;
      6'b111011 : memoutb1_2 = 34'b0100010000110110101110111001110110;
      6'b111100 : memoutb1_2 = 34'b0100000011001100011001000011101011;
      6'b111101 : memoutb1_2 = 34'b0100011110111010001010111001101101;
      6'b111110 : memoutb1_2 = 34'b0100101101001010111001110101110000;
      6'b111111 : memoutb1_2 = 34'b0101001000111000101011101011110010;
      default : memoutb1_2 = 34'b0101001000111000101011101011110010;
    endcase
  end

  assign mem_addr_3 = {delay_pipeline[543], delay_pipeline[511], delay_pipeline[479], delay_pipeline[447], delay_pipeline[415], delay_pipeline[383]};

  always @(mem_addr_3)
  begin
    case(mem_addr_3)
      6'b000000 : memoutb1_3 = 33'b000000000000000000000000000000000;
      6'b000001 : memoutb1_3 = 33'b000111000000001111100110001111100;
      6'b000010 : memoutb1_3 = 33'b000101001111110100000110010000101;
      6'b000011 : memoutb1_3 = 33'b001100010000000011101100100000001;
      6'b000100 : memoutb1_3 = 33'b000011011101101110001110110000010;
      6'b000101 : memoutb1_3 = 33'b001010011101111101110100111111110;
      6'b000110 : memoutb1_3 = 33'b001000101101100010010101000000111;
      6'b000111 : memoutb1_3 = 33'b001111101101110001111011010000011;
      6'b001000 : memoutb1_3 = 33'b000001111111011000001100010111011;
      6'b001001 : memoutb1_3 = 33'b001000111111100111110010100110111;
      6'b001010 : memoutb1_3 = 33'b000111001111001100010010101000000;
      6'b001011 : memoutb1_3 = 33'b001110001111011011111000110111100;
      6'b001100 : memoutb1_3 = 33'b000101011101000110011011000111101;
      6'b001101 : memoutb1_3 = 33'b001100011101010110000001010111001;
      6'b001110 : memoutb1_3 = 33'b001010101100111010100001011000010;
      6'b001111 : memoutb1_3 = 33'b010001101101001010000111100111110;
      6'b010000 : memoutb1_3 = 33'b000000111110011010000101011001011;
      6'b010001 : memoutb1_3 = 33'b000111111110101001101011101000111;
      6'b010010 : memoutb1_3 = 33'b000110001110001110001011101010000;
      6'b010011 : memoutb1_3 = 33'b001101001110011101110001111001100;
      6'b010100 : memoutb1_3 = 33'b000100011100001000010100001001101;
      6'b010101 : memoutb1_3 = 33'b001011011100010111111010011001001;
      6'b010110 : memoutb1_3 = 33'b001001101011111100011010011010010;
      6'b010111 : memoutb1_3 = 33'b010000101100001100000000101001110;
      6'b011000 : memoutb1_3 = 33'b000010111101110010010001110000110;
      6'b011001 : memoutb1_3 = 33'b001001111110000001111000000000010;
      6'b011010 : memoutb1_3 = 33'b001000001101100110011000000001011;
      6'b011011 : memoutb1_3 = 33'b001111001101110101111110010000111;
      6'b011100 : memoutb1_3 = 33'b000110011011100000100000100001000;
      6'b011101 : memoutb1_3 = 33'b001101011011110000000110110000100;
      6'b011110 : memoutb1_3 = 33'b001011101011010100100110110001101;
      6'b011111 : memoutb1_3 = 33'b010010101011100100001101000001001;
      6'b100000 : memoutb1_3 = 33'b000000011001001111101111111110010;
      6'b100001 : memoutb1_3 = 33'b000111011001011111010110001101110;
      6'b100010 : memoutb1_3 = 33'b000101101001000011110110001110111;
      6'b100011 : memoutb1_3 = 33'b001100101001010011011100011110011;
      6'b100100 : memoutb1_3 = 33'b000011110110111101111110101110100;
      6'b100101 : memoutb1_3 = 33'b001010110111001101100100111110000;
      6'b100110 : memoutb1_3 = 33'b001001000110110010000100111111001;
      6'b100111 : memoutb1_3 = 33'b010000000111000001101011001110101;
      6'b101000 : memoutb1_3 = 33'b000010011000100111111100010101101;
      6'b101001 : memoutb1_3 = 33'b001001011000110111100010100101001;
      6'b101010 : memoutb1_3 = 33'b000111101000011100000010100110010;
      6'b101011 : memoutb1_3 = 33'b001110101000101011101000110101110;
      6'b101100 : memoutb1_3 = 33'b000101110110010110001011000101111;
      6'b101101 : memoutb1_3 = 33'b001100110110100101110001010101011;
      6'b101110 : memoutb1_3 = 33'b001011000110001010010001010110100;
      6'b101111 : memoutb1_3 = 33'b010010000110011001110111100110000;
      6'b110000 : memoutb1_3 = 33'b000001010111101001110101010111101;
      6'b110001 : memoutb1_3 = 33'b001000010111111001011011100111001;
      6'b110010 : memoutb1_3 = 33'b000110100111011101111011101000010;
      6'b110011 : memoutb1_3 = 33'b001101100111101101100001110111110;
      6'b110100 : memoutb1_3 = 33'b000100110101011000000100000111111;
      6'b110101 : memoutb1_3 = 33'b001011110101100111101010010111011;
      6'b110110 : memoutb1_3 = 33'b001010000101001100001010011000100;
      6'b110111 : memoutb1_3 = 33'b010001000101011011110000101000000;
      6'b111000 : memoutb1_3 = 33'b000011010111000010000001101111000;
      6'b111001 : memoutb1_3 = 33'b001010010111010001100111111110100;
      6'b111010 : memoutb1_3 = 33'b001000100110110110000111111111101;
      6'b111011 : memoutb1_3 = 33'b001111100111000101101110001111001;
      6'b111100 : memoutb1_3 = 33'b000110110100110000010000011111010;
      6'b111101 : memoutb1_3 = 33'b001101110100111111110110101110110;
      6'b111110 : memoutb1_3 = 33'b001100000100100100010110101111111;
      6'b111111 : memoutb1_3 = 33'b010011000100110011111100111111011;
      default : memoutb1_3 = 33'b010011000100110011111100111111011;
    endcase
  end

  assign mem_addr_4 = {delay_pipeline[639], delay_pipeline[607], delay_pipeline[575]};

  always @(mem_addr_4)
  begin
    case(mem_addr_4)
      3'b000 : memoutb1_4 = 26'b00000000000000000000000000;
      3'b001 : memoutb1_4 = 26'b00111111110001110101101110;
      3'b010 : memoutb1_4 = 26'b00001110000011110110010000;
      3'b011 : memoutb1_4 = 26'b01001101110101101011111110;
      3'b100 : memoutb1_4 = 26'b00000001100101001100110010;
      3'b101 : memoutb1_4 = 26'b01000001010111000010100000;
      3'b110 : memoutb1_4 = 26'b00001111101001000011000010;
      3'b111 : memoutb1_4 = 26'b01001111011010111000110000;
      default : memoutb1_4 = 26'b01001111011010111000110000;
    endcase
  end

  assign add_signext = $signed({{4{memoutb1_1[29]}}, memoutb1_1});
  assign add_signext_1 = memoutb1_2;
  assign sum1_1 = add_signext + add_signext_1;

  assign add_signext_2 = memoutb1_3;
  assign add_signext_3 = $signed({{7{memoutb1_4[25]}}, memoutb1_4});
  assign sum1_2 = add_signext_2 + add_signext_3;

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
        end
      end
    end // temp_process1

  assign add_signext_4 = sumpipe1_1;
  assign add_signext_5 = $signed({{1{sumpipe1_2[33]}}, sumpipe1_2});
  assign sum2_1 = add_signext_4 + add_signext_5;

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
        end
      end
    end // temp_process2

  assign memoutb1 = sumpipe2_1[33:0];

  //  Shift and add the LUT results to compute the scaled accumulated sum

  assign memoutb1_cast = $signed({memoutb1[33:0], 31'b0000000000000000000000000000000});

  assign acc_out_shft = $signed({{1{acc_out[65]}}, acc_out[65:1]});

  assign add_signext_6 = acc_out_shft;
  assign add_signext_7 = memoutb1_cast;
  assign add_temp = add_signext_6 + add_signext_7;
  assign addsub_add = add_temp[65:0];

  assign sub_signext = acc_out_shft;
  assign sub_signext_1 = memoutb1_cast;
  assign sub_temp = sub_signext - sub_signext_1;
  assign addsub_sub = sub_temp[65:0];

  assign add_sub_out = (phase_1 == 1'b1) ? addsub_sub :
                      addsub_add;

  assign acc_in = (phase_2 == 1'b1) ? memoutb1_cast :
            add_sub_out;

  always @ (posedge clk or posedge reset)
    begin: Acc_reg_process
      if (reset == 1'b1) begin
        acc_out <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          acc_out <= acc_in;
        end
      end
    end // Acc_reg_process

  always @ (posedge clk or posedge reset)
    begin: Finalsum_reg_process
      if (reset == 1'b1) begin
        final_acc_out <= 0;
      end
      else begin
        if (phase_2 == 1'b1) begin
          final_acc_out <= acc_out;
        end
      end
    end // Finalsum_reg_process

  assign output_da = final_acc_out;

  assign output_typeconvert = $signed({{3{output_da[65]}}, output_da});

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (phase_31 == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // fir_20_32b_da
