// -------------------------------------------------------------
//
// Module: fir_20_16b_fcsd
// Generated by MATLAB(R) 9.12 and Filter Design HDL Coder 3.1.11.
// Generated on: 2023-06-21 23:55:58
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// CoeffMultipliers: Factored-CSD
// FIRAdderStyle: tree
// OptimizeForHDL: on
// TargetDirectory: W:\Nikos\UTh\Σχεδίαση Επεξεργαστών\Project\FIR_20_Order\factored_csd\16b_fixed_point
// AddPipelineRegisters: on
// Name: fir_20_16b_fcsd
// InputDataType: numerictype(1,16,0)
// TargetLanguage: Verilog
// TestBenchName: fir_20_16b_fcsd_tb
// TestBenchStimulus: impulse step ramp chirp noise 

// Filter Specifications:
//
// Sample Rate     : 46 kHz
// Response        : Lowpass
// Specification   : N,Fp,Fst,Ap
// Stopband Edge   : 9.6 kHz
// Filter Order    : 20
// Passband Edge   : 8 kHz
// Passband Ripple : 60 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 21
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module fir_20_16b_fcsd
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16
  output  signed [36:0] filter_out; //sfix37_En16

////////////////////////////////////////////////////////////////
//Module Architecture: fir_20_16b_fcsd
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b0000000000000110; //sfix16_En16
  parameter signed [15:0] coeff2 = 16'b0000000000111000; //sfix16_En16
  parameter signed [15:0] coeff3 = 16'b0000000011111111; //sfix16_En16
  parameter signed [15:0] coeff4 = 16'b0000001100101000; //sfix16_En16
  parameter signed [15:0] coeff5 = 16'b0000011111001101; //sfix16_En16
  parameter signed [15:0] coeff6 = 16'b0000111111101100; //sfix16_En16
  parameter signed [15:0] coeff7 = 16'b0001101110110111; //sfix16_En16
  parameter signed [15:0] coeff8 = 16'b0010100111111010; //sfix16_En16
  parameter signed [15:0] coeff9 = 16'b0011100000001000; //sfix16_En16
  parameter signed [15:0] coeff10 = 16'b0100001001110000; //sfix16_En16
  parameter signed [15:0] coeff11 = 16'b0100011001001010; //sfix16_En16
  parameter signed [15:0] coeff12 = 16'b0100001001110000; //sfix16_En16
  parameter signed [15:0] coeff13 = 16'b0011100000001000; //sfix16_En16
  parameter signed [15:0] coeff14 = 16'b0010100111111010; //sfix16_En16
  parameter signed [15:0] coeff15 = 16'b0001101110110111; //sfix16_En16
  parameter signed [15:0] coeff16 = 16'b0000111111101100; //sfix16_En16
  parameter signed [15:0] coeff17 = 16'b0000011111001101; //sfix16_En16
  parameter signed [15:0] coeff18 = 16'b0000001100101000; //sfix16_En16
  parameter signed [15:0] coeff19 = 16'b0000000011111111; //sfix16_En16
  parameter signed [15:0] coeff20 = 16'b0000000000111000; //sfix16_En16
  parameter signed [15:0] coeff21 = 16'b0000000000000110; //sfix16_En16

  // Signals
  reg  signed [15:0] delay_pipeline [0:20] ; // sfix16
  wire signed [31:0] product21; // sfix32_En16
  wire signed [19:0] mulcsd_temp; // sfix20_En16
  wire signed [31:0] product20; // sfix32_En16
  wire signed [22:0] mulcsd_temp_1; // sfix23_En16
  wire signed [31:0] product19; // sfix32_En16
  wire signed [24:0] mulcsd_temp_2; // sfix25_En16
  wire signed [31:0] product18; // sfix32_En16
  wire signed [26:0] mulcsd_temp_3; // sfix27_En16
  wire signed [31:0] product17; // sfix32_En16
  wire signed [27:0] mulcsd_temp_4; // sfix28_En16
  wire signed [31:0] product16; // sfix32_En16
  wire signed [28:0] mulcsd_temp_5; // sfix29_En16
  wire signed [31:0] product15; // sfix32_En16
  wire signed [29:0] mulcsd_temp_6; // sfix30_En16
  wire signed [31:0] product14; // sfix32_En16
  wire signed [29:0] mulcsd_temp_7; // sfix30_En16
  wire signed [31:0] product13; // sfix32_En16
  wire signed [30:0] mulcsd_temp_8; // sfix31_En16
  wire signed [31:0] product12; // sfix32_En16
  wire signed [30:0] mulcsd_temp_9; // sfix31_En16
  wire signed [31:0] product11; // sfix32_En16
  wire signed [30:0] mulcsd_temp_10; // sfix31_En16
  wire signed [31:0] product10; // sfix32_En16
  wire signed [30:0] mulcsd_temp_11; // sfix31_En16
  wire signed [31:0] product9; // sfix32_En16
  wire signed [30:0] mulcsd_temp_12; // sfix31_En16
  wire signed [31:0] product8; // sfix32_En16
  wire signed [29:0] mulcsd_temp_13; // sfix30_En16
  wire signed [31:0] product7; // sfix32_En16
  wire signed [29:0] mulcsd_temp_14; // sfix30_En16
  wire signed [31:0] product6; // sfix32_En16
  wire signed [28:0] mulcsd_temp_15; // sfix29_En16
  wire signed [31:0] product5; // sfix32_En16
  wire signed [27:0] mulcsd_temp_16; // sfix28_En16
  wire signed [31:0] product4; // sfix32_En16
  wire signed [26:0] mulcsd_temp_17; // sfix27_En16
  wire signed [31:0] product3; // sfix32_En16
  wire signed [24:0] mulcsd_temp_18; // sfix25_En16
  wire signed [31:0] product2; // sfix32_En16
  wire signed [22:0] mulcsd_temp_19; // sfix23_En16
  wire signed [31:0] product1; // sfix32_En16
  wire signed [19:0] mulcsd_temp_20; // sfix20_En16
  wire signed [36:0] sum_final; // sfix37_En16
  wire signed [36:0] sum1_1; // sfix37_En16
  wire signed [31:0] add_signext; // sfix32_En16
  wire signed [31:0] add_signext_1; // sfix32_En16
  wire signed [32:0] add_temp; // sfix33_En16
  reg  signed [36:0] sumpipe1_1; // sfix37_En16
  wire signed [36:0] sum1_2; // sfix37_En16
  wire signed [31:0] add_signext_2; // sfix32_En16
  wire signed [31:0] add_signext_3; // sfix32_En16
  wire signed [32:0] add_temp_1; // sfix33_En16
  reg  signed [36:0] sumpipe1_2; // sfix37_En16
  wire signed [36:0] sum1_3; // sfix37_En16
  wire signed [31:0] add_signext_4; // sfix32_En16
  wire signed [31:0] add_signext_5; // sfix32_En16
  wire signed [32:0] add_temp_2; // sfix33_En16
  reg  signed [36:0] sumpipe1_3; // sfix37_En16
  wire signed [36:0] sum1_4; // sfix37_En16
  wire signed [31:0] add_signext_6; // sfix32_En16
  wire signed [31:0] add_signext_7; // sfix32_En16
  wire signed [32:0] add_temp_3; // sfix33_En16
  reg  signed [36:0] sumpipe1_4; // sfix37_En16
  wire signed [36:0] sum1_5; // sfix37_En16
  wire signed [31:0] add_signext_8; // sfix32_En16
  wire signed [31:0] add_signext_9; // sfix32_En16
  wire signed [32:0] add_temp_4; // sfix33_En16
  reg  signed [36:0] sumpipe1_5; // sfix37_En16
  wire signed [36:0] sum1_6; // sfix37_En16
  wire signed [31:0] add_signext_10; // sfix32_En16
  wire signed [31:0] add_signext_11; // sfix32_En16
  wire signed [32:0] add_temp_5; // sfix33_En16
  reg  signed [36:0] sumpipe1_6; // sfix37_En16
  wire signed [36:0] sum1_7; // sfix37_En16
  wire signed [31:0] add_signext_12; // sfix32_En16
  wire signed [31:0] add_signext_13; // sfix32_En16
  wire signed [32:0] add_temp_6; // sfix33_En16
  reg  signed [36:0] sumpipe1_7; // sfix37_En16
  wire signed [36:0] sum1_8; // sfix37_En16
  wire signed [31:0] add_signext_14; // sfix32_En16
  wire signed [31:0] add_signext_15; // sfix32_En16
  wire signed [32:0] add_temp_7; // sfix33_En16
  reg  signed [36:0] sumpipe1_8; // sfix37_En16
  wire signed [36:0] sum1_9; // sfix37_En16
  wire signed [31:0] add_signext_16; // sfix32_En16
  wire signed [31:0] add_signext_17; // sfix32_En16
  wire signed [32:0] add_temp_8; // sfix33_En16
  reg  signed [36:0] sumpipe1_9; // sfix37_En16
  wire signed [36:0] sum1_10; // sfix37_En16
  wire signed [31:0] add_signext_18; // sfix32_En16
  wire signed [31:0] add_signext_19; // sfix32_En16
  wire signed [32:0] add_temp_9; // sfix33_En16
  reg  signed [36:0] sumpipe1_10; // sfix37_En16
  reg  signed [31:0] sumpipe1_11; // sfix32_En16
  wire signed [36:0] sum2_1; // sfix37_En16
  wire signed [36:0] add_signext_20; // sfix37_En16
  wire signed [36:0] add_signext_21; // sfix37_En16
  wire signed [37:0] add_temp_10; // sfix38_En16
  reg  signed [36:0] sumpipe2_1; // sfix37_En16
  wire signed [36:0] sum2_2; // sfix37_En16
  wire signed [36:0] add_signext_22; // sfix37_En16
  wire signed [36:0] add_signext_23; // sfix37_En16
  wire signed [37:0] add_temp_11; // sfix38_En16
  reg  signed [36:0] sumpipe2_2; // sfix37_En16
  wire signed [36:0] sum2_3; // sfix37_En16
  wire signed [36:0] add_signext_24; // sfix37_En16
  wire signed [36:0] add_signext_25; // sfix37_En16
  wire signed [37:0] add_temp_12; // sfix38_En16
  reg  signed [36:0] sumpipe2_3; // sfix37_En16
  wire signed [36:0] sum2_4; // sfix37_En16
  wire signed [36:0] add_signext_26; // sfix37_En16
  wire signed [36:0] add_signext_27; // sfix37_En16
  wire signed [37:0] add_temp_13; // sfix38_En16
  reg  signed [36:0] sumpipe2_4; // sfix37_En16
  wire signed [36:0] sum2_5; // sfix37_En16
  wire signed [36:0] add_signext_28; // sfix37_En16
  wire signed [36:0] add_signext_29; // sfix37_En16
  wire signed [37:0] add_temp_14; // sfix38_En16
  reg  signed [36:0] sumpipe2_5; // sfix37_En16
  reg  signed [31:0] sumpipe2_6; // sfix32_En16
  wire signed [36:0] sum3_1; // sfix37_En16
  wire signed [36:0] add_signext_30; // sfix37_En16
  wire signed [36:0] add_signext_31; // sfix37_En16
  wire signed [37:0] add_temp_15; // sfix38_En16
  reg  signed [36:0] sumpipe3_1; // sfix37_En16
  wire signed [36:0] sum3_2; // sfix37_En16
  wire signed [36:0] add_signext_32; // sfix37_En16
  wire signed [36:0] add_signext_33; // sfix37_En16
  wire signed [37:0] add_temp_16; // sfix38_En16
  reg  signed [36:0] sumpipe3_2; // sfix37_En16
  wire signed [36:0] sum3_3; // sfix37_En16
  wire signed [36:0] add_signext_34; // sfix37_En16
  wire signed [36:0] add_signext_35; // sfix37_En16
  wire signed [37:0] add_temp_17; // sfix38_En16
  reg  signed [36:0] sumpipe3_3; // sfix37_En16
  wire signed [36:0] sum4_1; // sfix37_En16
  wire signed [36:0] add_signext_36; // sfix37_En16
  wire signed [36:0] add_signext_37; // sfix37_En16
  wire signed [37:0] add_temp_18; // sfix38_En16
  reg  signed [36:0] sumpipe4_1; // sfix37_En16
  reg  signed [36:0] sumpipe4_2; // sfix37_En16
  wire signed [36:0] sum5_1; // sfix37_En16
  wire signed [36:0] add_signext_38; // sfix37_En16
  wire signed [36:0] add_signext_39; // sfix37_En16
  wire signed [37:0] add_temp_19; // sfix38_En16
  reg  signed [36:0] sumpipe5_1; // sfix37_En16
  reg  signed [36:0] output_register; // sfix37_En16

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
        end
      end
    end // Delay_Pipeline_process


// For FCSD of 6, optimizing to CSD due to lower cost
  assign mulcsd_temp = 
        $signed({delay_pipeline[20], 3'b000}) -
        $signed({delay_pipeline[20], 1'b0});
  assign product21 = $signed({{12{mulcsd_temp[19]}}, mulcsd_temp});

// For FCSD of 56, optimizing to CSD due to lower cost
  assign mulcsd_temp_1 = 
        $signed({delay_pipeline[19], 6'b000000}) -
        $signed({delay_pipeline[19], 3'b000});
  assign product20 = $signed({{9{mulcsd_temp_1[22]}}, mulcsd_temp_1});

// For FCSD of 255, optimizing to CSD due to lower cost
  assign mulcsd_temp_2 = 
        $signed({delay_pipeline[18], 8'b00000000}) -
        delay_pipeline[18];
  assign product19 = $signed({{7{mulcsd_temp_2[24]}}, mulcsd_temp_2});

// For FCSD of 808, optimizing to CSD due to lower cost
  assign mulcsd_temp_3 = 
        $signed({delay_pipeline[17], 10'b0000000000}) -
        $signed({delay_pipeline[17], 8'b00000000}) +
        $signed({delay_pipeline[17], 5'b00000}) +
        $signed({delay_pipeline[17], 3'b000});
  assign product18 = $signed({{5{mulcsd_temp_3[26]}}, mulcsd_temp_3});

// For FCSD of 1997, optimizing to CSD due to lower cost
  assign mulcsd_temp_4 = 
        $signed({delay_pipeline[16], 11'b00000000000}) -
        $signed({delay_pipeline[16], 6'b000000}) +
        $signed({delay_pipeline[16], 4'b0000}) -
        $signed({delay_pipeline[16], 2'b00}) +
        delay_pipeline[16];
  assign product17 = $signed({{4{mulcsd_temp_4[27]}}, mulcsd_temp_4});

// For FCSD of 4076, optimizing to CSD due to lower cost
  assign mulcsd_temp_5 = 
        $signed({delay_pipeline[15], 12'b000000000000}) -
        $signed({delay_pipeline[15], 5'b00000}) +
        $signed({delay_pipeline[15], 4'b0000}) -
        $signed({delay_pipeline[15], 2'b00});
  assign product16 = $signed({{3{mulcsd_temp_5[28]}}, mulcsd_temp_5});

// For FCSD of 7095, optimizing to CSD due to lower cost
  assign mulcsd_temp_6 = 
        $signed({delay_pipeline[14], 13'b0000000000000}) -
        $signed({delay_pipeline[14], 11'b00000000000}) +
        $signed({delay_pipeline[14], 10'b0000000000}) -
        $signed({delay_pipeline[14], 7'b0000000}) +
        $signed({delay_pipeline[14], 6'b000000}) -
        $signed({delay_pipeline[14], 4'b0000}) +
        $signed({delay_pipeline[14], 3'b000}) -
        delay_pipeline[14];
  assign product15 = $signed({{2{mulcsd_temp_6[29]}}, mulcsd_temp_6});

// For FCSD of 10746, optimizing to CSD due to lower cost
  assign mulcsd_temp_7 = 
        $signed({delay_pipeline[13], 13'b0000000000000}) +
        $signed({delay_pipeline[13], 11'b00000000000}) +
        $signed({delay_pipeline[13], 9'b000000000}) -
        $signed({delay_pipeline[13], 3'b000}) +
        $signed({delay_pipeline[13], 1'b0});
  assign product14 = $signed({{2{mulcsd_temp_7[29]}}, mulcsd_temp_7});

// For FCSD of 14344, optimizing to CSD due to lower cost
  assign mulcsd_temp_8 = 
        $signed({delay_pipeline[12], 14'b00000000000000}) -
        $signed({delay_pipeline[12], 11'b00000000000}) +
        $signed({delay_pipeline[12], 3'b000});
  assign product13 = $signed({{1{mulcsd_temp_8[30]}}, mulcsd_temp_8});

// For FCSD of 17008, optimizing to CSD due to lower cost
  assign mulcsd_temp_9 = 
        $signed({delay_pipeline[11], 14'b00000000000000}) +
        $signed({delay_pipeline[11], 9'b000000000}) +
        $signed({delay_pipeline[11], 7'b0000000}) -
        $signed({delay_pipeline[11], 4'b0000});
  assign product12 = $signed({{1{mulcsd_temp_9[30]}}, mulcsd_temp_9});

// For FCSD of 17994, optimizing to CSD due to lower cost
  assign mulcsd_temp_10 = 
        $signed({delay_pipeline[10], 14'b00000000000000}) +
        $signed({delay_pipeline[10], 11'b00000000000}) -
        $signed({delay_pipeline[10], 9'b000000000}) +
        $signed({delay_pipeline[10], 6'b000000}) +
        $signed({delay_pipeline[10], 3'b000}) +
        $signed({delay_pipeline[10], 1'b0});
  assign product11 = $signed({{1{mulcsd_temp_10[30]}}, mulcsd_temp_10});

// For FCSD of 17008, optimizing to CSD due to lower cost
  assign mulcsd_temp_11 = 
        $signed({delay_pipeline[9], 14'b00000000000000}) +
        $signed({delay_pipeline[9], 9'b000000000}) +
        $signed({delay_pipeline[9], 7'b0000000}) -
        $signed({delay_pipeline[9], 4'b0000});
  assign product10 = $signed({{1{mulcsd_temp_11[30]}}, mulcsd_temp_11});

// For FCSD of 14344, optimizing to CSD due to lower cost
  assign mulcsd_temp_12 = 
        $signed({delay_pipeline[8], 14'b00000000000000}) -
        $signed({delay_pipeline[8], 11'b00000000000}) +
        $signed({delay_pipeline[8], 3'b000});
  assign product9 = $signed({{1{mulcsd_temp_12[30]}}, mulcsd_temp_12});

// For FCSD of 10746, optimizing to CSD due to lower cost
  assign mulcsd_temp_13 = 
        $signed({delay_pipeline[7], 13'b0000000000000}) +
        $signed({delay_pipeline[7], 11'b00000000000}) +
        $signed({delay_pipeline[7], 9'b000000000}) -
        $signed({delay_pipeline[7], 3'b000}) +
        $signed({delay_pipeline[7], 1'b0});
  assign product8 = $signed({{2{mulcsd_temp_13[29]}}, mulcsd_temp_13});

// For FCSD of 7095, optimizing to CSD due to lower cost
  assign mulcsd_temp_14 = 
        $signed({delay_pipeline[6], 13'b0000000000000}) -
        $signed({delay_pipeline[6], 11'b00000000000}) +
        $signed({delay_pipeline[6], 10'b0000000000}) -
        $signed({delay_pipeline[6], 7'b0000000}) +
        $signed({delay_pipeline[6], 6'b000000}) -
        $signed({delay_pipeline[6], 4'b0000}) +
        $signed({delay_pipeline[6], 3'b000}) -
        delay_pipeline[6];
  assign product7 = $signed({{2{mulcsd_temp_14[29]}}, mulcsd_temp_14});

// For FCSD of 4076, optimizing to CSD due to lower cost
  assign mulcsd_temp_15 = 
        $signed({delay_pipeline[5], 12'b000000000000}) -
        $signed({delay_pipeline[5], 5'b00000}) +
        $signed({delay_pipeline[5], 4'b0000}) -
        $signed({delay_pipeline[5], 2'b00});
  assign product6 = $signed({{3{mulcsd_temp_15[28]}}, mulcsd_temp_15});

// For FCSD of 1997, optimizing to CSD due to lower cost
  assign mulcsd_temp_16 = 
        $signed({delay_pipeline[4], 11'b00000000000}) -
        $signed({delay_pipeline[4], 6'b000000}) +
        $signed({delay_pipeline[4], 4'b0000}) -
        $signed({delay_pipeline[4], 2'b00}) +
        delay_pipeline[4];
  assign product5 = $signed({{4{mulcsd_temp_16[27]}}, mulcsd_temp_16});

// For FCSD of 808, optimizing to CSD due to lower cost
  assign mulcsd_temp_17 = 
        $signed({delay_pipeline[3], 10'b0000000000}) -
        $signed({delay_pipeline[3], 8'b00000000}) +
        $signed({delay_pipeline[3], 5'b00000}) +
        $signed({delay_pipeline[3], 3'b000});
  assign product4 = $signed({{5{mulcsd_temp_17[26]}}, mulcsd_temp_17});

// For FCSD of 255, optimizing to CSD due to lower cost
  assign mulcsd_temp_18 = 
        $signed({delay_pipeline[2], 8'b00000000}) -
        delay_pipeline[2];
  assign product3 = $signed({{7{mulcsd_temp_18[24]}}, mulcsd_temp_18});

// For FCSD of 56, optimizing to CSD due to lower cost
  assign mulcsd_temp_19 = 
        $signed({delay_pipeline[1], 6'b000000}) -
        $signed({delay_pipeline[1], 3'b000});
  assign product2 = $signed({{9{mulcsd_temp_19[22]}}, mulcsd_temp_19});

// For FCSD of 6, optimizing to CSD due to lower cost
  assign mulcsd_temp_20 = 
        $signed({delay_pipeline[0], 3'b000}) -
        $signed({delay_pipeline[0], 1'b0});
  assign product1 = $signed({{12{mulcsd_temp_20[19]}}, mulcsd_temp_20});

  assign add_signext = product21;
  assign add_signext_1 = product20;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{4{add_temp[32]}}, add_temp});

  assign add_signext_2 = product19;
  assign add_signext_3 = product18;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{4{add_temp_1[32]}}, add_temp_1});

  assign add_signext_4 = product17;
  assign add_signext_5 = product16;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{4{add_temp_2[32]}}, add_temp_2});

  assign add_signext_6 = product15;
  assign add_signext_7 = product14;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{4{add_temp_3[32]}}, add_temp_3});

  assign add_signext_8 = product13;
  assign add_signext_9 = product12;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{4{add_temp_4[32]}}, add_temp_4});

  assign add_signext_10 = product11;
  assign add_signext_11 = product10;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{4{add_temp_5[32]}}, add_temp_5});

  assign add_signext_12 = product9;
  assign add_signext_13 = product8;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{4{add_temp_6[32]}}, add_temp_6});

  assign add_signext_14 = product7;
  assign add_signext_15 = product6;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum1_8 = $signed({{4{add_temp_7[32]}}, add_temp_7});

  assign add_signext_16 = product5;
  assign add_signext_17 = product4;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum1_9 = $signed({{4{add_temp_8[32]}}, add_temp_8});

  assign add_signext_18 = product3;
  assign add_signext_19 = product2;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum1_10 = $signed({{4{add_temp_9[32]}}, add_temp_9});

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
        sumpipe1_5 <= 0;
        sumpipe1_6 <= 0;
        sumpipe1_7 <= 0;
        sumpipe1_8 <= 0;
        sumpipe1_9 <= 0;
        sumpipe1_10 <= 0;
        sumpipe1_11 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= sum1_4;
          sumpipe1_5 <= sum1_5;
          sumpipe1_6 <= sum1_6;
          sumpipe1_7 <= sum1_7;
          sumpipe1_8 <= sum1_8;
          sumpipe1_9 <= sum1_9;
          sumpipe1_10 <= sum1_10;
          sumpipe1_11 <= product1;
        end
      end
    end // temp_process1

  assign add_signext_20 = sumpipe1_1;
  assign add_signext_21 = sumpipe1_2;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum2_1 = add_temp_10[36:0];

  assign add_signext_22 = sumpipe1_3;
  assign add_signext_23 = sumpipe1_4;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum2_2 = add_temp_11[36:0];

  assign add_signext_24 = sumpipe1_5;
  assign add_signext_25 = sumpipe1_6;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum2_3 = add_temp_12[36:0];

  assign add_signext_26 = sumpipe1_7;
  assign add_signext_27 = sumpipe1_8;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum2_4 = add_temp_13[36:0];

  assign add_signext_28 = sumpipe1_9;
  assign add_signext_29 = sumpipe1_10;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum2_5 = add_temp_14[36:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
        sumpipe2_3 <= 0;
        sumpipe2_4 <= 0;
        sumpipe2_5 <= 0;
        sumpipe2_6 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
          sumpipe2_3 <= sum2_3;
          sumpipe2_4 <= sum2_4;
          sumpipe2_5 <= sum2_5;
          sumpipe2_6 <= sumpipe1_11;
        end
      end
    end // temp_process2

  assign add_signext_30 = sumpipe2_1;
  assign add_signext_31 = sumpipe2_2;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum3_1 = add_temp_15[36:0];

  assign add_signext_32 = sumpipe2_3;
  assign add_signext_33 = sumpipe2_4;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum3_2 = add_temp_16[36:0];

  assign add_signext_34 = sumpipe2_5;
  assign add_signext_35 = $signed({{5{sumpipe2_6[31]}}, sumpipe2_6});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum3_3 = add_temp_17[36:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
        sumpipe3_2 <= 0;
        sumpipe3_3 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
          sumpipe3_2 <= sum3_2;
          sumpipe3_3 <= sum3_3;
        end
      end
    end // temp_process3

  assign add_signext_36 = sumpipe3_1;
  assign add_signext_37 = sumpipe3_2;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum4_1 = add_temp_18[36:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        sumpipe4_1 <= 0;
        sumpipe4_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe4_1 <= sum4_1;
          sumpipe4_2 <= sumpipe3_3;
        end
      end
    end // temp_process4

  assign add_signext_38 = sumpipe4_1;
  assign add_signext_39 = sumpipe4_2;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum5_1 = add_temp_19[36:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        sumpipe5_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe5_1 <= sum5_1;
        end
      end
    end // temp_process5

  assign sum_final = sumpipe5_1;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum_final;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // fir_20_16b_fcsd
