// -------------------------------------------------------------
//
// Module: fir_30_32b_fcsd
// Generated by MATLAB(R) 9.12 and Filter Design HDL Coder 3.1.11.
// Generated on: 2023-06-22 12:04:22
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// CoeffMultipliers: Factored-CSD
// FIRAdderStyle: tree
// OptimizeForHDL: on
// TargetDirectory: W:\Nikos\UTh\Σχεδίαση Επεξεργαστών\Project\FIR_30_Order\factored_csd\32b_floating_point
// AddPipelineRegisters: on
// Name: fir_30_32b_fcsd
// InputDataType: numerictype(1,32,0)
// TargetLanguage: Verilog
// TestBenchName: fir_30_32b_fcsd_tb
// TestBenchStimulus: impulse step ramp chirp noise 

// Filter Specifications:
//
// Sample Rate     : 46 kHz
// Response        : Lowpass
// Specification   : N,Fp,Fst,Ap
// Stopband Edge   : 9.6 kHz
// Filter Order    : 30
// Passband Edge   : 8 kHz
// Passband Ripple : 60 dB
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 31
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s32,32 -> [-5.000000e-01 5.000000e-01)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module fir_30_32b_fcsd
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [31:0] filter_in; //sfix32
  output  signed [68:0] filter_out; //sfix69_En32

////////////////////////////////////////////////////////////////
//Module Architecture: fir_30_32b_fcsd
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [31:0] coeff1 = 32'h00080BCA; //sfix32_En32
  parameter signed [31:0] coeff2 = 32'h002D0B63; //sfix32_En32
  parameter signed [31:0] coeff3 = 32'h0082077A; //sfix32_En32
  parameter signed [31:0] coeff4 = 32'h00DE7270; //sfix32_En32
  parameter signed [31:0] coeff5 = 32'h0089CB98; //sfix32_En32
  parameter signed [31:0] coeff6 = 32'hFE1BB4B2; //sfix32_En32
  parameter signed [31:0] coeff7 = 32'hF7FE98CE; //sfix32_En32
  parameter signed [31:0] coeff8 = 32'hEDB86A4E; //sfix32_En32
  parameter signed [31:0] coeff9 = 32'hE1693960; //sfix32_En32
  parameter signed [31:0] coeff10 = 32'hD84C73DD; //sfix32_En32
  parameter signed [31:0] coeff11 = 32'hD92A9720; //sfix32_En32
  parameter signed [31:0] coeff12 = 32'hE8D75F22; //sfix32_En32
  parameter signed [31:0] coeff13 = 32'h067835C2; //sfix32_En32
  parameter signed [31:0] coeff14 = 32'h2A1D8FC5; //sfix32_En32
  parameter signed [31:0] coeff15 = 32'h47474270; //sfix32_En32
  parameter signed [31:0] coeff16 = 32'h52892F7C; //sfix32_En32
  parameter signed [31:0] coeff17 = 32'h47474270; //sfix32_En32
  parameter signed [31:0] coeff18 = 32'h2A1D8FC5; //sfix32_En32
  parameter signed [31:0] coeff19 = 32'h067835C2; //sfix32_En32
  parameter signed [31:0] coeff20 = 32'hE8D75F22; //sfix32_En32
  parameter signed [31:0] coeff21 = 32'hD92A9720; //sfix32_En32
  parameter signed [31:0] coeff22 = 32'hD84C73DD; //sfix32_En32
  parameter signed [31:0] coeff23 = 32'hE1693960; //sfix32_En32
  parameter signed [31:0] coeff24 = 32'hEDB86A4E; //sfix32_En32
  parameter signed [31:0] coeff25 = 32'hF7FE98CE; //sfix32_En32
  parameter signed [31:0] coeff26 = 32'hFE1BB4B2; //sfix32_En32
  parameter signed [31:0] coeff27 = 32'h0089CB98; //sfix32_En32
  parameter signed [31:0] coeff28 = 32'h00DE7270; //sfix32_En32
  parameter signed [31:0] coeff29 = 32'h0082077A; //sfix32_En32
  parameter signed [31:0] coeff30 = 32'h002D0B63; //sfix32_En32
  parameter signed [31:0] coeff31 = 32'h00080BCA; //sfix32_En32

  // Signals
  reg  signed [31:0] delay_pipeline [0:30] ; // sfix32
  wire signed [63:0] product31; // sfix64_En32
  wire signed [51:0] mulcsd_temp; // sfix52_En32
  wire signed [63:0] product30; // sfix64_En32
  wire signed [51:0] factoredcsd_temp; // sfix52_En20
  wire signed [51:0] mulcsd_temp_1; // sfix52_En20
  wire signed [53:0] factoredcsd_temp_1; // sfix54_En23
  wire signed [54:0] mulcsd_temp_2; // sfix55_En23
  wire signed [53:0] factoredcsd_temp_2; // sfix54_En32
  wire signed [63:0] product29; // sfix64_En32
  wire signed [55:0] mulcsd_temp_3; // sfix56_En32
  wire signed [63:0] product28; // sfix64_En32
  wire signed [56:0] mulcsd_temp_4; // sfix57_En32
  wire signed [63:0] product27; // sfix64_En32
  wire signed [55:0] mulcsd_temp_5; // sfix56_En32
  wire signed [63:0] product26; // sfix64_En32
  wire signed [57:0] mulcsd_temp_6; // sfix58_En32
  wire signed [63:0] product25; // sfix64_En32
  wire signed [59:0] mulcsd_temp_7; // sfix60_En32
  wire signed [63:0] product24; // sfix64_En32
  wire signed [60:0] mulcsd_temp_8; // sfix61_En32
  wire signed [63:0] product23; // sfix64_En32
  wire signed [50:0] factoredcsd_temp_3; // sfix51_En19
  wire signed [50:0] mulcsd_temp_9; // sfix51_En19
  wire signed [56:0] factoredcsd_temp_4; // sfix57_En25
  wire signed [57:0] mulcsd_temp_10; // sfix58_En25
  wire signed [60:0] factoredcsd_temp_5; // sfix61_En32
  wire signed [61:0] unaryminus_temp; // sfix62_En32
  wire signed [63:0] product22; // sfix64_En32
  wire signed [61:0] mulcsd_temp_11; // sfix62_En32
  wire signed [63:0] product21; // sfix64_En32
  wire signed [53:0] factoredcsd_temp_6; // sfix54_En22
  wire signed [53:0] mulcsd_temp_12; // sfix54_En22
  wire signed [57:0] factoredcsd_temp_7; // sfix58_En26
  wire signed [57:0] mulcsd_temp_13; // sfix58_En26
  wire signed [61:0] factoredcsd_temp_8; // sfix62_En32
  wire signed [62:0] unaryminus_temp_1; // sfix63_En32
  wire signed [63:0] product20; // sfix64_En32
  wire signed [60:0] mulcsd_temp_14; // sfix61_En32
  wire signed [63:0] product19; // sfix64_En32
  wire signed [59:0] mulcsd_temp_15; // sfix60_En32
  wire signed [63:0] product18; // sfix64_En32
  wire signed [61:0] mulcsd_temp_16; // sfix62_En32
  wire signed [63:0] product17; // sfix64_En32
  wire signed [62:0] mulcsd_temp_17; // sfix63_En32
  wire signed [63:0] product16; // sfix64_En32
  wire signed [62:0] mulcsd_temp_18; // sfix63_En32
  wire signed [63:0] product15; // sfix64_En32
  wire signed [62:0] mulcsd_temp_19; // sfix63_En32
  wire signed [63:0] product14; // sfix64_En32
  wire signed [61:0] mulcsd_temp_20; // sfix62_En32
  wire signed [63:0] product13; // sfix64_En32
  wire signed [59:0] mulcsd_temp_21; // sfix60_En32
  wire signed [63:0] product12; // sfix64_En32
  wire signed [60:0] mulcsd_temp_22; // sfix61_En32
  wire signed [63:0] product11; // sfix64_En32
  wire signed [53:0] factoredcsd_temp_9; // sfix54_En22
  wire signed [53:0] mulcsd_temp_23; // sfix54_En22
  wire signed [57:0] factoredcsd_temp_10; // sfix58_En26
  wire signed [57:0] mulcsd_temp_24; // sfix58_En26
  wire signed [61:0] factoredcsd_temp_11; // sfix62_En32
  wire signed [62:0] unaryminus_temp_2; // sfix63_En32
  wire signed [63:0] product10; // sfix64_En32
  wire signed [61:0] mulcsd_temp_25; // sfix62_En32
  wire signed [63:0] product9; // sfix64_En32
  wire signed [50:0] factoredcsd_temp_12; // sfix51_En19
  wire signed [50:0] mulcsd_temp_26; // sfix51_En19
  wire signed [56:0] factoredcsd_temp_13; // sfix57_En25
  wire signed [57:0] mulcsd_temp_27; // sfix58_En25
  wire signed [60:0] factoredcsd_temp_14; // sfix61_En32
  wire signed [61:0] unaryminus_temp_3; // sfix62_En32
  wire signed [63:0] product8; // sfix64_En32
  wire signed [60:0] mulcsd_temp_28; // sfix61_En32
  wire signed [63:0] product7; // sfix64_En32
  wire signed [59:0] mulcsd_temp_29; // sfix60_En32
  wire signed [63:0] product6; // sfix64_En32
  wire signed [57:0] mulcsd_temp_30; // sfix58_En32
  wire signed [63:0] product5; // sfix64_En32
  wire signed [55:0] mulcsd_temp_31; // sfix56_En32
  wire signed [63:0] product4; // sfix64_En32
  wire signed [56:0] mulcsd_temp_32; // sfix57_En32
  wire signed [63:0] product3; // sfix64_En32
  wire signed [55:0] mulcsd_temp_33; // sfix56_En32
  wire signed [63:0] product2; // sfix64_En32
  wire signed [51:0] factoredcsd_temp_15; // sfix52_En20
  wire signed [51:0] mulcsd_temp_34; // sfix52_En20
  wire signed [53:0] factoredcsd_temp_16; // sfix54_En23
  wire signed [54:0] mulcsd_temp_35; // sfix55_En23
  wire signed [53:0] factoredcsd_temp_17; // sfix54_En32
  wire signed [63:0] product1; // sfix64_En32
  wire signed [51:0] mulcsd_temp_36; // sfix52_En32
  wire signed [68:0] sum_final; // sfix69_En32
  wire signed [68:0] sum1_1; // sfix69_En32
  wire signed [63:0] add_signext; // sfix64_En32
  wire signed [63:0] add_signext_1; // sfix64_En32
  wire signed [64:0] add_temp; // sfix65_En32
  reg  signed [68:0] sumpipe1_1; // sfix69_En32
  wire signed [68:0] sum1_2; // sfix69_En32
  wire signed [63:0] add_signext_2; // sfix64_En32
  wire signed [63:0] add_signext_3; // sfix64_En32
  wire signed [64:0] add_temp_1; // sfix65_En32
  reg  signed [68:0] sumpipe1_2; // sfix69_En32
  wire signed [68:0] sum1_3; // sfix69_En32
  wire signed [63:0] add_signext_4; // sfix64_En32
  wire signed [63:0] add_signext_5; // sfix64_En32
  wire signed [64:0] add_temp_2; // sfix65_En32
  reg  signed [68:0] sumpipe1_3; // sfix69_En32
  wire signed [68:0] sum1_4; // sfix69_En32
  wire signed [63:0] add_signext_6; // sfix64_En32
  wire signed [63:0] add_signext_7; // sfix64_En32
  wire signed [64:0] add_temp_3; // sfix65_En32
  reg  signed [68:0] sumpipe1_4; // sfix69_En32
  wire signed [68:0] sum1_5; // sfix69_En32
  wire signed [63:0] add_signext_8; // sfix64_En32
  wire signed [63:0] add_signext_9; // sfix64_En32
  wire signed [64:0] add_temp_4; // sfix65_En32
  reg  signed [68:0] sumpipe1_5; // sfix69_En32
  wire signed [68:0] sum1_6; // sfix69_En32
  wire signed [63:0] add_signext_10; // sfix64_En32
  wire signed [63:0] add_signext_11; // sfix64_En32
  wire signed [64:0] add_temp_5; // sfix65_En32
  reg  signed [68:0] sumpipe1_6; // sfix69_En32
  wire signed [68:0] sum1_7; // sfix69_En32
  wire signed [63:0] add_signext_12; // sfix64_En32
  wire signed [63:0] add_signext_13; // sfix64_En32
  wire signed [64:0] add_temp_6; // sfix65_En32
  reg  signed [68:0] sumpipe1_7; // sfix69_En32
  wire signed [68:0] sum1_8; // sfix69_En32
  wire signed [63:0] add_signext_14; // sfix64_En32
  wire signed [63:0] add_signext_15; // sfix64_En32
  wire signed [64:0] add_temp_7; // sfix65_En32
  reg  signed [68:0] sumpipe1_8; // sfix69_En32
  wire signed [68:0] sum1_9; // sfix69_En32
  wire signed [63:0] add_signext_16; // sfix64_En32
  wire signed [63:0] add_signext_17; // sfix64_En32
  wire signed [64:0] add_temp_8; // sfix65_En32
  reg  signed [68:0] sumpipe1_9; // sfix69_En32
  wire signed [68:0] sum1_10; // sfix69_En32
  wire signed [63:0] add_signext_18; // sfix64_En32
  wire signed [63:0] add_signext_19; // sfix64_En32
  wire signed [64:0] add_temp_9; // sfix65_En32
  reg  signed [68:0] sumpipe1_10; // sfix69_En32
  wire signed [68:0] sum1_11; // sfix69_En32
  wire signed [63:0] add_signext_20; // sfix64_En32
  wire signed [63:0] add_signext_21; // sfix64_En32
  wire signed [64:0] add_temp_10; // sfix65_En32
  reg  signed [68:0] sumpipe1_11; // sfix69_En32
  wire signed [68:0] sum1_12; // sfix69_En32
  wire signed [63:0] add_signext_22; // sfix64_En32
  wire signed [63:0] add_signext_23; // sfix64_En32
  wire signed [64:0] add_temp_11; // sfix65_En32
  reg  signed [68:0] sumpipe1_12; // sfix69_En32
  wire signed [68:0] sum1_13; // sfix69_En32
  wire signed [63:0] add_signext_24; // sfix64_En32
  wire signed [63:0] add_signext_25; // sfix64_En32
  wire signed [64:0] add_temp_12; // sfix65_En32
  reg  signed [68:0] sumpipe1_13; // sfix69_En32
  wire signed [68:0] sum1_14; // sfix69_En32
  wire signed [63:0] add_signext_26; // sfix64_En32
  wire signed [63:0] add_signext_27; // sfix64_En32
  wire signed [64:0] add_temp_13; // sfix65_En32
  reg  signed [68:0] sumpipe1_14; // sfix69_En32
  wire signed [68:0] sum1_15; // sfix69_En32
  wire signed [63:0] add_signext_28; // sfix64_En32
  wire signed [63:0] add_signext_29; // sfix64_En32
  wire signed [64:0] add_temp_14; // sfix65_En32
  reg  signed [68:0] sumpipe1_15; // sfix69_En32
  reg  signed [63:0] sumpipe1_16; // sfix64_En32
  wire signed [68:0] sum2_1; // sfix69_En32
  wire signed [68:0] add_signext_30; // sfix69_En32
  wire signed [68:0] add_signext_31; // sfix69_En32
  wire signed [69:0] add_temp_15; // sfix70_En32
  reg  signed [68:0] sumpipe2_1; // sfix69_En32
  wire signed [68:0] sum2_2; // sfix69_En32
  wire signed [68:0] add_signext_32; // sfix69_En32
  wire signed [68:0] add_signext_33; // sfix69_En32
  wire signed [69:0] add_temp_16; // sfix70_En32
  reg  signed [68:0] sumpipe2_2; // sfix69_En32
  wire signed [68:0] sum2_3; // sfix69_En32
  wire signed [68:0] add_signext_34; // sfix69_En32
  wire signed [68:0] add_signext_35; // sfix69_En32
  wire signed [69:0] add_temp_17; // sfix70_En32
  reg  signed [68:0] sumpipe2_3; // sfix69_En32
  wire signed [68:0] sum2_4; // sfix69_En32
  wire signed [68:0] add_signext_36; // sfix69_En32
  wire signed [68:0] add_signext_37; // sfix69_En32
  wire signed [69:0] add_temp_18; // sfix70_En32
  reg  signed [68:0] sumpipe2_4; // sfix69_En32
  wire signed [68:0] sum2_5; // sfix69_En32
  wire signed [68:0] add_signext_38; // sfix69_En32
  wire signed [68:0] add_signext_39; // sfix69_En32
  wire signed [69:0] add_temp_19; // sfix70_En32
  reg  signed [68:0] sumpipe2_5; // sfix69_En32
  wire signed [68:0] sum2_6; // sfix69_En32
  wire signed [68:0] add_signext_40; // sfix69_En32
  wire signed [68:0] add_signext_41; // sfix69_En32
  wire signed [69:0] add_temp_20; // sfix70_En32
  reg  signed [68:0] sumpipe2_6; // sfix69_En32
  wire signed [68:0] sum2_7; // sfix69_En32
  wire signed [68:0] add_signext_42; // sfix69_En32
  wire signed [68:0] add_signext_43; // sfix69_En32
  wire signed [69:0] add_temp_21; // sfix70_En32
  reg  signed [68:0] sumpipe2_7; // sfix69_En32
  wire signed [68:0] sum2_8; // sfix69_En32
  wire signed [68:0] add_signext_44; // sfix69_En32
  wire signed [68:0] add_signext_45; // sfix69_En32
  wire signed [69:0] add_temp_22; // sfix70_En32
  reg  signed [68:0] sumpipe2_8; // sfix69_En32
  wire signed [68:0] sum3_1; // sfix69_En32
  wire signed [68:0] add_signext_46; // sfix69_En32
  wire signed [68:0] add_signext_47; // sfix69_En32
  wire signed [69:0] add_temp_23; // sfix70_En32
  reg  signed [68:0] sumpipe3_1; // sfix69_En32
  wire signed [68:0] sum3_2; // sfix69_En32
  wire signed [68:0] add_signext_48; // sfix69_En32
  wire signed [68:0] add_signext_49; // sfix69_En32
  wire signed [69:0] add_temp_24; // sfix70_En32
  reg  signed [68:0] sumpipe3_2; // sfix69_En32
  wire signed [68:0] sum3_3; // sfix69_En32
  wire signed [68:0] add_signext_50; // sfix69_En32
  wire signed [68:0] add_signext_51; // sfix69_En32
  wire signed [69:0] add_temp_25; // sfix70_En32
  reg  signed [68:0] sumpipe3_3; // sfix69_En32
  wire signed [68:0] sum3_4; // sfix69_En32
  wire signed [68:0] add_signext_52; // sfix69_En32
  wire signed [68:0] add_signext_53; // sfix69_En32
  wire signed [69:0] add_temp_26; // sfix70_En32
  reg  signed [68:0] sumpipe3_4; // sfix69_En32
  wire signed [68:0] sum4_1; // sfix69_En32
  wire signed [68:0] add_signext_54; // sfix69_En32
  wire signed [68:0] add_signext_55; // sfix69_En32
  wire signed [69:0] add_temp_27; // sfix70_En32
  reg  signed [68:0] sumpipe4_1; // sfix69_En32
  wire signed [68:0] sum4_2; // sfix69_En32
  wire signed [68:0] add_signext_56; // sfix69_En32
  wire signed [68:0] add_signext_57; // sfix69_En32
  wire signed [69:0] add_temp_28; // sfix70_En32
  reg  signed [68:0] sumpipe4_2; // sfix69_En32
  wire signed [68:0] sum5_1; // sfix69_En32
  wire signed [68:0] add_signext_58; // sfix69_En32
  wire signed [68:0] add_signext_59; // sfix69_En32
  wire signed [69:0] add_temp_29; // sfix70_En32
  reg  signed [68:0] sumpipe5_1; // sfix69_En32
  reg  signed [68:0] output_register; // sfix69_En32

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
        end
      end
    end // Delay_Pipeline_process


// For FCSD of 527306, optimizing to CSD due to lower cost
  assign mulcsd_temp = 
        $signed({delay_pipeline[30], 19'b0000000000000000000}) +
        $signed({delay_pipeline[30], 11'b00000000000}) +
        $signed({delay_pipeline[30], 10'b0000000000}) -
        $signed({delay_pipeline[30], 6'b000000}) +
        $signed({delay_pipeline[30], 3'b000}) +
        $signed({delay_pipeline[30], 1'b0});
  assign product31 = $signed({{12{mulcsd_temp[51]}}, mulcsd_temp});

// For FCSD of 2952035, using factorization: 590407 5 
// 
  assign mulcsd_temp_1 = 
        $signed({delay_pipeline[29], 19'b0000000000000000000}) +
        $signed({delay_pipeline[29], 16'b0000000000000000}) +
        $signed({delay_pipeline[29], 9'b000000000}) +
        $signed({delay_pipeline[29], 6'b000000}) +
        $signed({delay_pipeline[29], 3'b000}) -
        delay_pipeline[29];
  assign factoredcsd_temp = mulcsd_temp_1;

  assign mulcsd_temp_2 = 
        $signed({factoredcsd_temp, 2'b00}) +
        factoredcsd_temp;
  assign factoredcsd_temp_1 = mulcsd_temp_2[53:0];

  assign factoredcsd_temp_2 = factoredcsd_temp_1;

  assign product30 = $signed({{10{factoredcsd_temp_2[53]}}, factoredcsd_temp_2});

// For FCSD of 8521594, optimizing to CSD due to lower cost
  assign mulcsd_temp_3 = 
        $signed({delay_pipeline[28], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[28], 17'b00000000000000000}) +
        $signed({delay_pipeline[28], 11'b00000000000}) -
        $signed({delay_pipeline[28], 8'b00000000}) +
        $signed({delay_pipeline[28], 7'b0000000}) -
        $signed({delay_pipeline[28], 3'b000}) +
        $signed({delay_pipeline[28], 1'b0});
  assign product29 = $signed({{8{mulcsd_temp_3[55]}}, mulcsd_temp_3});

// For FCSD of 14578288, optimizing to CSD due to lower cost
  assign mulcsd_temp_4 = 
        $signed({delay_pipeline[27], 24'b000000000000000000000000}) -
        $signed({delay_pipeline[27], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[27], 21'b000000000000000000000}) -
        $signed({delay_pipeline[27], 17'b00000000000000000}) +
        $signed({delay_pipeline[27], 15'b000000000000000}) -
        $signed({delay_pipeline[27], 12'b000000000000}) +
        $signed({delay_pipeline[27], 9'b000000000}) +
        $signed({delay_pipeline[27], 7'b0000000}) -
        $signed({delay_pipeline[27], 4'b0000});
  assign product28 = $signed({{7{mulcsd_temp_4[56]}}, mulcsd_temp_4});

// For FCSD of 9030552, optimizing to CSD due to lower cost
  assign mulcsd_temp_5 = 
        $signed({delay_pipeline[26], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[26], 19'b0000000000000000000}) +
        $signed({delay_pipeline[26], 17'b00000000000000000}) -
        $signed({delay_pipeline[26], 14'b00000000000000}) +
        $signed({delay_pipeline[26], 11'b00000000000}) +
        $signed({delay_pipeline[26], 10'b0000000000}) -
        $signed({delay_pipeline[26], 7'b0000000}) +
        $signed({delay_pipeline[26], 5'b00000}) -
        $signed({delay_pipeline[26], 3'b000});
  assign product27 = $signed({{8{mulcsd_temp_5[55]}}, mulcsd_temp_5});

// For FCSD of -31738702, optimizing to CSD due to lower cost
  assign mulcsd_temp_6 = - (
        $signed({delay_pipeline[25], 25'b0000000000000000000000000}) -
        $signed({delay_pipeline[25], 21'b000000000000000000000}) +
        $signed({delay_pipeline[25], 18'b000000000000000000}) +
        $signed({delay_pipeline[25], 14'b00000000000000}) +
        $signed({delay_pipeline[25], 11'b00000000000}) +
        $signed({delay_pipeline[25], 10'b0000000000}) -
        $signed({delay_pipeline[25], 8'b00000000}) +
        $signed({delay_pipeline[25], 6'b000000}) +
        $signed({delay_pipeline[25], 4'b0000}) -
        $signed({delay_pipeline[25], 1'b0}));
  assign product26 = $signed({{6{mulcsd_temp_6[57]}}, mulcsd_temp_6});

// For FCSD of -134309682, optimizing to CSD due to lower cost
  assign mulcsd_temp_7 = - (
        $signed({delay_pipeline[24], 27'b000000000000000000000000000}) +
        $signed({delay_pipeline[24], 16'b0000000000000000}) +
        $signed({delay_pipeline[24], 15'b000000000000000}) -
        $signed({delay_pipeline[24], 13'b0000000000000}) +
        $signed({delay_pipeline[24], 11'b00000000000}) -
        $signed({delay_pipeline[24], 8'b00000000}) +
        $signed({delay_pipeline[24], 6'b000000}) -
        $signed({delay_pipeline[24], 4'b0000}) +
        $signed({delay_pipeline[24], 1'b0}));
  assign product25 = $signed({{4{mulcsd_temp_7[59]}}, mulcsd_temp_7});

// For FCSD of -306681266, optimizing to CSD due to lower cost
  assign mulcsd_temp_8 = - (
        $signed({delay_pipeline[23], 28'b0000000000000000000000000000}) +
        $signed({delay_pipeline[23], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[23], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[23], 19'b0000000000000000000}) -
        $signed({delay_pipeline[23], 15'b000000000000000}) +
        $signed({delay_pipeline[23], 12'b000000000000}) +
        $signed({delay_pipeline[23], 10'b0000000000}) +
        $signed({delay_pipeline[23], 9'b000000000}) -
        $signed({delay_pipeline[23], 7'b0000000}) +
        $signed({delay_pipeline[23], 6'b000000}) -
        $signed({delay_pipeline[23], 4'b0000}) +
        $signed({delay_pipeline[23], 1'b0}));
  assign product24 = $signed({{3{mulcsd_temp_8[60]}}, mulcsd_temp_8});

// For FCSD of -513197728, using factorization: 302593 53 2 2 2 2 2 
// 
  assign mulcsd_temp_9 = 
        $signed({delay_pipeline[22], 18'b000000000000000000}) +
        $signed({delay_pipeline[22], 15'b000000000000000}) +
        $signed({delay_pipeline[22], 13'b0000000000000}) -
        $signed({delay_pipeline[22], 9'b000000000}) +
        delay_pipeline[22];
  assign factoredcsd_temp_3 = mulcsd_temp_9;

  assign mulcsd_temp_10 = 
        $signed({factoredcsd_temp_3, 6'b000000}) -
        $signed({factoredcsd_temp_3, 4'b0000}) +
        $signed({factoredcsd_temp_3, 2'b00}) +
        factoredcsd_temp_3;
  assign factoredcsd_temp_4 = mulcsd_temp_10[56:0];

  assign factoredcsd_temp_5 = $signed({factoredcsd_temp_4[55:0], 5'b00000});

  assign unaryminus_temp = (factoredcsd_temp_5==61'b1000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, factoredcsd_temp_5}) : -factoredcsd_temp_5;
  assign product23 = $signed({{2{unaryminus_temp[61]}}, unaryminus_temp});

// For FCSD of -666078243, optimizing to CSD due to lower cost
  assign mulcsd_temp_11 = - (
        $signed({delay_pipeline[21], 29'b00000000000000000000000000000}) +
        $signed({delay_pipeline[21], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[21], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[21], 22'b0000000000000000000000}) -
        $signed({delay_pipeline[21], 20'b00000000000000000000}) +
        $signed({delay_pipeline[21], 18'b000000000000000000}) -
        $signed({delay_pipeline[21], 15'b000000000000000}) +
        $signed({delay_pipeline[21], 12'b000000000000}) -
        $signed({delay_pipeline[21], 10'b0000000000}) +
        $signed({delay_pipeline[21], 5'b00000}) +
        $signed({delay_pipeline[21], 2'b00}) -
        delay_pipeline[21]);
  assign product22 = $signed({{2{mulcsd_temp_11[61]}}, mulcsd_temp_11});

// For FCSD of -651520224, using factorization: 2262223 9 2 2 2 2 2 
// 
  assign mulcsd_temp_12 = 
        $signed({delay_pipeline[20], 21'b000000000000000000000}) +
        $signed({delay_pipeline[20], 17'b00000000000000000}) +
        $signed({delay_pipeline[20], 15'b000000000000000}) +
        $signed({delay_pipeline[20], 10'b0000000000}) +
        $signed({delay_pipeline[20], 8'b00000000}) -
        $signed({delay_pipeline[20], 6'b000000}) +
        $signed({delay_pipeline[20], 4'b0000}) -
        delay_pipeline[20];
  assign factoredcsd_temp_6 = mulcsd_temp_12;

  assign mulcsd_temp_13 = 
        $signed({factoredcsd_temp_6, 3'b000}) +
        factoredcsd_temp_6;
  assign factoredcsd_temp_7 = mulcsd_temp_13;

  assign factoredcsd_temp_8 = $signed({factoredcsd_temp_7[56:0], 5'b00000});

  assign unaryminus_temp_1 = (factoredcsd_temp_8==62'b10000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, factoredcsd_temp_8}) : -factoredcsd_temp_8;
  assign product21 = $signed({{1{unaryminus_temp_1[62]}}, unaryminus_temp_1});

// For FCSD of -388538590, optimizing to CSD due to lower cost
  assign mulcsd_temp_14 = - (
        $signed({delay_pipeline[19], 28'b0000000000000000000000000000}) +
        $signed({delay_pipeline[19], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[19], 24'b000000000000000000000000}) +
        $signed({delay_pipeline[19], 21'b000000000000000000000}) +
        $signed({delay_pipeline[19], 19'b0000000000000000000}) +
        $signed({delay_pipeline[19], 15'b000000000000000}) +
        $signed({delay_pipeline[19], 13'b0000000000000}) +
        $signed({delay_pipeline[19], 8'b00000000}) -
        $signed({delay_pipeline[19], 6'b000000}) +
        $signed({delay_pipeline[19], 5'b00000}) -
        $signed({delay_pipeline[19], 1'b0}));
  assign product20 = $signed({{3{mulcsd_temp_14[60]}}, mulcsd_temp_14});

// For FCSD of 108541378, optimizing to CSD due to lower cost
  assign mulcsd_temp_15 = 
        $signed({delay_pipeline[18], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[18], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[18], 23'b00000000000000000000000}) -
        $signed({delay_pipeline[18], 19'b0000000000000000000}) +
        $signed({delay_pipeline[18], 14'b00000000000000}) -
        $signed({delay_pipeline[18], 12'b000000000000}) +
        $signed({delay_pipeline[18], 10'b0000000000}) +
        $signed({delay_pipeline[18], 9'b000000000}) -
        $signed({delay_pipeline[18], 6'b000000}) +
        $signed({delay_pipeline[18], 1'b0});
  assign product19 = $signed({{4{mulcsd_temp_15[59]}}, mulcsd_temp_15});

// For FCSD of 706580421, optimizing to CSD due to lower cost
  assign mulcsd_temp_16 = 
        $signed({delay_pipeline[17], 29'b00000000000000000000000000000}) +
        $signed({delay_pipeline[17], 27'b000000000000000000000000000}) +
        $signed({delay_pipeline[17], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[17], 21'b000000000000000000000}) -
        $signed({delay_pipeline[17], 18'b000000000000000000}) +
        $signed({delay_pipeline[17], 17'b00000000000000000}) -
        $signed({delay_pipeline[17], 15'b000000000000000}) +
        $signed({delay_pipeline[17], 12'b000000000000}) -
        $signed({delay_pipeline[17], 6'b000000}) +
        $signed({delay_pipeline[17], 2'b00}) +
        delay_pipeline[17];
  assign product18 = $signed({{2{mulcsd_temp_16[61]}}, mulcsd_temp_16});

// For FCSD of 1195852400, optimizing to CSD due to lower cost
  assign mulcsd_temp_17 = 
        $signed({delay_pipeline[16], 30'b000000000000000000000000000000}) +
        $signed({delay_pipeline[16], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[16], 24'b000000000000000000000000}) +
        $signed({delay_pipeline[16], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[16], 19'b0000000000000000000}) -
        $signed({delay_pipeline[16], 16'b0000000000000000}) +
        $signed({delay_pipeline[16], 14'b00000000000000}) +
        $signed({delay_pipeline[16], 9'b000000000}) +
        $signed({delay_pipeline[16], 7'b0000000}) -
        $signed({delay_pipeline[16], 4'b0000});
  assign product17 = $signed({{1{mulcsd_temp_17[62]}}, mulcsd_temp_17});

// For FCSD of 1384722300, optimizing to CSD due to lower cost
  assign mulcsd_temp_18 = 
        $signed({delay_pipeline[15], 30'b000000000000000000000000000000}) +
        $signed({delay_pipeline[15], 28'b0000000000000000000000000000}) +
        $signed({delay_pipeline[15], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[15], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[15], 19'b0000000000000000000}) +
        $signed({delay_pipeline[15], 16'b0000000000000000}) +
        $signed({delay_pipeline[15], 13'b0000000000000}) +
        $signed({delay_pipeline[15], 12'b000000000000}) -
        $signed({delay_pipeline[15], 8'b00000000}) +
        $signed({delay_pipeline[15], 7'b0000000}) -
        $signed({delay_pipeline[15], 2'b00});
  assign product16 = $signed({{1{mulcsd_temp_18[62]}}, mulcsd_temp_18});

// For FCSD of 1195852400, optimizing to CSD due to lower cost
  assign mulcsd_temp_19 = 
        $signed({delay_pipeline[14], 30'b000000000000000000000000000000}) +
        $signed({delay_pipeline[14], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[14], 24'b000000000000000000000000}) +
        $signed({delay_pipeline[14], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[14], 19'b0000000000000000000}) -
        $signed({delay_pipeline[14], 16'b0000000000000000}) +
        $signed({delay_pipeline[14], 14'b00000000000000}) +
        $signed({delay_pipeline[14], 9'b000000000}) +
        $signed({delay_pipeline[14], 7'b0000000}) -
        $signed({delay_pipeline[14], 4'b0000});
  assign product15 = $signed({{1{mulcsd_temp_19[62]}}, mulcsd_temp_19});

// For FCSD of 706580421, optimizing to CSD due to lower cost
  assign mulcsd_temp_20 = 
        $signed({delay_pipeline[13], 29'b00000000000000000000000000000}) +
        $signed({delay_pipeline[13], 27'b000000000000000000000000000}) +
        $signed({delay_pipeline[13], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[13], 21'b000000000000000000000}) -
        $signed({delay_pipeline[13], 18'b000000000000000000}) +
        $signed({delay_pipeline[13], 17'b00000000000000000}) -
        $signed({delay_pipeline[13], 15'b000000000000000}) +
        $signed({delay_pipeline[13], 12'b000000000000}) -
        $signed({delay_pipeline[13], 6'b000000}) +
        $signed({delay_pipeline[13], 2'b00}) +
        delay_pipeline[13];
  assign product14 = $signed({{2{mulcsd_temp_20[61]}}, mulcsd_temp_20});

// For FCSD of 108541378, optimizing to CSD due to lower cost
  assign mulcsd_temp_21 = 
        $signed({delay_pipeline[12], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[12], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[12], 23'b00000000000000000000000}) -
        $signed({delay_pipeline[12], 19'b0000000000000000000}) +
        $signed({delay_pipeline[12], 14'b00000000000000}) -
        $signed({delay_pipeline[12], 12'b000000000000}) +
        $signed({delay_pipeline[12], 10'b0000000000}) +
        $signed({delay_pipeline[12], 9'b000000000}) -
        $signed({delay_pipeline[12], 6'b000000}) +
        $signed({delay_pipeline[12], 1'b0});
  assign product13 = $signed({{4{mulcsd_temp_21[59]}}, mulcsd_temp_21});

// For FCSD of -388538590, optimizing to CSD due to lower cost
  assign mulcsd_temp_22 = - (
        $signed({delay_pipeline[11], 28'b0000000000000000000000000000}) +
        $signed({delay_pipeline[11], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[11], 24'b000000000000000000000000}) +
        $signed({delay_pipeline[11], 21'b000000000000000000000}) +
        $signed({delay_pipeline[11], 19'b0000000000000000000}) +
        $signed({delay_pipeline[11], 15'b000000000000000}) +
        $signed({delay_pipeline[11], 13'b0000000000000}) +
        $signed({delay_pipeline[11], 8'b00000000}) -
        $signed({delay_pipeline[11], 6'b000000}) +
        $signed({delay_pipeline[11], 5'b00000}) -
        $signed({delay_pipeline[11], 1'b0}));
  assign product12 = $signed({{3{mulcsd_temp_22[60]}}, mulcsd_temp_22});

// For FCSD of -651520224, using factorization: 2262223 9 2 2 2 2 2 
// 
  assign mulcsd_temp_23 = 
        $signed({delay_pipeline[10], 21'b000000000000000000000}) +
        $signed({delay_pipeline[10], 17'b00000000000000000}) +
        $signed({delay_pipeline[10], 15'b000000000000000}) +
        $signed({delay_pipeline[10], 10'b0000000000}) +
        $signed({delay_pipeline[10], 8'b00000000}) -
        $signed({delay_pipeline[10], 6'b000000}) +
        $signed({delay_pipeline[10], 4'b0000}) -
        delay_pipeline[10];
  assign factoredcsd_temp_9 = mulcsd_temp_23;

  assign mulcsd_temp_24 = 
        $signed({factoredcsd_temp_9, 3'b000}) +
        factoredcsd_temp_9;
  assign factoredcsd_temp_10 = mulcsd_temp_24;

  assign factoredcsd_temp_11 = $signed({factoredcsd_temp_10[56:0], 5'b00000});

  assign unaryminus_temp_2 = (factoredcsd_temp_11==62'b10000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, factoredcsd_temp_11}) : -factoredcsd_temp_11;
  assign product11 = $signed({{1{unaryminus_temp_2[62]}}, unaryminus_temp_2});

// For FCSD of -666078243, optimizing to CSD due to lower cost
  assign mulcsd_temp_25 = - (
        $signed({delay_pipeline[9], 29'b00000000000000000000000000000}) +
        $signed({delay_pipeline[9], 27'b000000000000000000000000000}) -
        $signed({delay_pipeline[9], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[9], 22'b0000000000000000000000}) -
        $signed({delay_pipeline[9], 20'b00000000000000000000}) +
        $signed({delay_pipeline[9], 18'b000000000000000000}) -
        $signed({delay_pipeline[9], 15'b000000000000000}) +
        $signed({delay_pipeline[9], 12'b000000000000}) -
        $signed({delay_pipeline[9], 10'b0000000000}) +
        $signed({delay_pipeline[9], 5'b00000}) +
        $signed({delay_pipeline[9], 2'b00}) -
        delay_pipeline[9]);
  assign product10 = $signed({{2{mulcsd_temp_25[61]}}, mulcsd_temp_25});

// For FCSD of -513197728, using factorization: 302593 53 2 2 2 2 2 
// 
  assign mulcsd_temp_26 = 
        $signed({delay_pipeline[8], 18'b000000000000000000}) +
        $signed({delay_pipeline[8], 15'b000000000000000}) +
        $signed({delay_pipeline[8], 13'b0000000000000}) -
        $signed({delay_pipeline[8], 9'b000000000}) +
        delay_pipeline[8];
  assign factoredcsd_temp_12 = mulcsd_temp_26;

  assign mulcsd_temp_27 = 
        $signed({factoredcsd_temp_12, 6'b000000}) -
        $signed({factoredcsd_temp_12, 4'b0000}) +
        $signed({factoredcsd_temp_12, 2'b00}) +
        factoredcsd_temp_12;
  assign factoredcsd_temp_13 = mulcsd_temp_27[56:0];

  assign factoredcsd_temp_14 = $signed({factoredcsd_temp_13[55:0], 5'b00000});

  assign unaryminus_temp_3 = (factoredcsd_temp_14==61'b1000000000000000000000000000000000000000000000000000000000000) ? $signed({1'b0, factoredcsd_temp_14}) : -factoredcsd_temp_14;
  assign product9 = $signed({{2{unaryminus_temp_3[61]}}, unaryminus_temp_3});

// For FCSD of -306681266, optimizing to CSD due to lower cost
  assign mulcsd_temp_28 = - (
        $signed({delay_pipeline[7], 28'b0000000000000000000000000000}) +
        $signed({delay_pipeline[7], 25'b0000000000000000000000000}) +
        $signed({delay_pipeline[7], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[7], 19'b0000000000000000000}) -
        $signed({delay_pipeline[7], 15'b000000000000000}) +
        $signed({delay_pipeline[7], 12'b000000000000}) +
        $signed({delay_pipeline[7], 10'b0000000000}) +
        $signed({delay_pipeline[7], 9'b000000000}) -
        $signed({delay_pipeline[7], 7'b0000000}) +
        $signed({delay_pipeline[7], 6'b000000}) -
        $signed({delay_pipeline[7], 4'b0000}) +
        $signed({delay_pipeline[7], 1'b0}));
  assign product8 = $signed({{3{mulcsd_temp_28[60]}}, mulcsd_temp_28});

// For FCSD of -134309682, optimizing to CSD due to lower cost
  assign mulcsd_temp_29 = - (
        $signed({delay_pipeline[6], 27'b000000000000000000000000000}) +
        $signed({delay_pipeline[6], 16'b0000000000000000}) +
        $signed({delay_pipeline[6], 15'b000000000000000}) -
        $signed({delay_pipeline[6], 13'b0000000000000}) +
        $signed({delay_pipeline[6], 11'b00000000000}) -
        $signed({delay_pipeline[6], 8'b00000000}) +
        $signed({delay_pipeline[6], 6'b000000}) -
        $signed({delay_pipeline[6], 4'b0000}) +
        $signed({delay_pipeline[6], 1'b0}));
  assign product7 = $signed({{4{mulcsd_temp_29[59]}}, mulcsd_temp_29});

// For FCSD of -31738702, optimizing to CSD due to lower cost
  assign mulcsd_temp_30 = - (
        $signed({delay_pipeline[5], 25'b0000000000000000000000000}) -
        $signed({delay_pipeline[5], 21'b000000000000000000000}) +
        $signed({delay_pipeline[5], 18'b000000000000000000}) +
        $signed({delay_pipeline[5], 14'b00000000000000}) +
        $signed({delay_pipeline[5], 11'b00000000000}) +
        $signed({delay_pipeline[5], 10'b0000000000}) -
        $signed({delay_pipeline[5], 8'b00000000}) +
        $signed({delay_pipeline[5], 6'b000000}) +
        $signed({delay_pipeline[5], 4'b0000}) -
        $signed({delay_pipeline[5], 1'b0}));
  assign product6 = $signed({{6{mulcsd_temp_30[57]}}, mulcsd_temp_30});

// For FCSD of 9030552, optimizing to CSD due to lower cost
  assign mulcsd_temp_31 = 
        $signed({delay_pipeline[4], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[4], 19'b0000000000000000000}) +
        $signed({delay_pipeline[4], 17'b00000000000000000}) -
        $signed({delay_pipeline[4], 14'b00000000000000}) +
        $signed({delay_pipeline[4], 11'b00000000000}) +
        $signed({delay_pipeline[4], 10'b0000000000}) -
        $signed({delay_pipeline[4], 7'b0000000}) +
        $signed({delay_pipeline[4], 5'b00000}) -
        $signed({delay_pipeline[4], 3'b000});
  assign product5 = $signed({{8{mulcsd_temp_31[55]}}, mulcsd_temp_31});

// For FCSD of 14578288, optimizing to CSD due to lower cost
  assign mulcsd_temp_32 = 
        $signed({delay_pipeline[3], 24'b000000000000000000000000}) -
        $signed({delay_pipeline[3], 22'b0000000000000000000000}) +
        $signed({delay_pipeline[3], 21'b000000000000000000000}) -
        $signed({delay_pipeline[3], 17'b00000000000000000}) +
        $signed({delay_pipeline[3], 15'b000000000000000}) -
        $signed({delay_pipeline[3], 12'b000000000000}) +
        $signed({delay_pipeline[3], 9'b000000000}) +
        $signed({delay_pipeline[3], 7'b0000000}) -
        $signed({delay_pipeline[3], 4'b0000});
  assign product4 = $signed({{7{mulcsd_temp_32[56]}}, mulcsd_temp_32});

// For FCSD of 8521594, optimizing to CSD due to lower cost
  assign mulcsd_temp_33 = 
        $signed({delay_pipeline[2], 23'b00000000000000000000000}) +
        $signed({delay_pipeline[2], 17'b00000000000000000}) +
        $signed({delay_pipeline[2], 11'b00000000000}) -
        $signed({delay_pipeline[2], 8'b00000000}) +
        $signed({delay_pipeline[2], 7'b0000000}) -
        $signed({delay_pipeline[2], 3'b000}) +
        $signed({delay_pipeline[2], 1'b0});
  assign product3 = $signed({{8{mulcsd_temp_33[55]}}, mulcsd_temp_33});

// For FCSD of 2952035, using factorization: 590407 5 
// 
  assign mulcsd_temp_34 = 
        $signed({delay_pipeline[1], 19'b0000000000000000000}) +
        $signed({delay_pipeline[1], 16'b0000000000000000}) +
        $signed({delay_pipeline[1], 9'b000000000}) +
        $signed({delay_pipeline[1], 6'b000000}) +
        $signed({delay_pipeline[1], 3'b000}) -
        delay_pipeline[1];
  assign factoredcsd_temp_15 = mulcsd_temp_34;

  assign mulcsd_temp_35 = 
        $signed({factoredcsd_temp_15, 2'b00}) +
        factoredcsd_temp_15;
  assign factoredcsd_temp_16 = mulcsd_temp_35[53:0];

  assign factoredcsd_temp_17 = factoredcsd_temp_16;

  assign product2 = $signed({{10{factoredcsd_temp_17[53]}}, factoredcsd_temp_17});

// For FCSD of 527306, optimizing to CSD due to lower cost
  assign mulcsd_temp_36 = 
        $signed({delay_pipeline[0], 19'b0000000000000000000}) +
        $signed({delay_pipeline[0], 11'b00000000000}) +
        $signed({delay_pipeline[0], 10'b0000000000}) -
        $signed({delay_pipeline[0], 6'b000000}) +
        $signed({delay_pipeline[0], 3'b000}) +
        $signed({delay_pipeline[0], 1'b0});
  assign product1 = $signed({{12{mulcsd_temp_36[51]}}, mulcsd_temp_36});

  assign add_signext = product31;
  assign add_signext_1 = product30;
  assign add_temp = add_signext + add_signext_1;
  assign sum1_1 = $signed({{4{add_temp[64]}}, add_temp});

  assign add_signext_2 = product29;
  assign add_signext_3 = product28;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum1_2 = $signed({{4{add_temp_1[64]}}, add_temp_1});

  assign add_signext_4 = product27;
  assign add_signext_5 = product26;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum1_3 = $signed({{4{add_temp_2[64]}}, add_temp_2});

  assign add_signext_6 = product25;
  assign add_signext_7 = product24;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum1_4 = $signed({{4{add_temp_3[64]}}, add_temp_3});

  assign add_signext_8 = product23;
  assign add_signext_9 = product22;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum1_5 = $signed({{4{add_temp_4[64]}}, add_temp_4});

  assign add_signext_10 = product21;
  assign add_signext_11 = product20;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum1_6 = $signed({{4{add_temp_5[64]}}, add_temp_5});

  assign add_signext_12 = product19;
  assign add_signext_13 = product18;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum1_7 = $signed({{4{add_temp_6[64]}}, add_temp_6});

  assign add_signext_14 = product17;
  assign add_signext_15 = product16;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum1_8 = $signed({{4{add_temp_7[64]}}, add_temp_7});

  assign add_signext_16 = product15;
  assign add_signext_17 = product14;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum1_9 = $signed({{4{add_temp_8[64]}}, add_temp_8});

  assign add_signext_18 = product13;
  assign add_signext_19 = product12;
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum1_10 = $signed({{4{add_temp_9[64]}}, add_temp_9});

  assign add_signext_20 = product11;
  assign add_signext_21 = product10;
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum1_11 = $signed({{4{add_temp_10[64]}}, add_temp_10});

  assign add_signext_22 = product9;
  assign add_signext_23 = product8;
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum1_12 = $signed({{4{add_temp_11[64]}}, add_temp_11});

  assign add_signext_24 = product7;
  assign add_signext_25 = product6;
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum1_13 = $signed({{4{add_temp_12[64]}}, add_temp_12});

  assign add_signext_26 = product5;
  assign add_signext_27 = product4;
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum1_14 = $signed({{4{add_temp_13[64]}}, add_temp_13});

  assign add_signext_28 = product3;
  assign add_signext_29 = product2;
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum1_15 = $signed({{4{add_temp_14[64]}}, add_temp_14});

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        sumpipe1_1 <= 0;
        sumpipe1_2 <= 0;
        sumpipe1_3 <= 0;
        sumpipe1_4 <= 0;
        sumpipe1_5 <= 0;
        sumpipe1_6 <= 0;
        sumpipe1_7 <= 0;
        sumpipe1_8 <= 0;
        sumpipe1_9 <= 0;
        sumpipe1_10 <= 0;
        sumpipe1_11 <= 0;
        sumpipe1_12 <= 0;
        sumpipe1_13 <= 0;
        sumpipe1_14 <= 0;
        sumpipe1_15 <= 0;
        sumpipe1_16 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe1_1 <= sum1_1;
          sumpipe1_2 <= sum1_2;
          sumpipe1_3 <= sum1_3;
          sumpipe1_4 <= sum1_4;
          sumpipe1_5 <= sum1_5;
          sumpipe1_6 <= sum1_6;
          sumpipe1_7 <= sum1_7;
          sumpipe1_8 <= sum1_8;
          sumpipe1_9 <= sum1_9;
          sumpipe1_10 <= sum1_10;
          sumpipe1_11 <= sum1_11;
          sumpipe1_12 <= sum1_12;
          sumpipe1_13 <= sum1_13;
          sumpipe1_14 <= sum1_14;
          sumpipe1_15 <= sum1_15;
          sumpipe1_16 <= product1;
        end
      end
    end // temp_process1

  assign add_signext_30 = sumpipe1_1;
  assign add_signext_31 = sumpipe1_2;
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum2_1 = add_temp_15[68:0];

  assign add_signext_32 = sumpipe1_3;
  assign add_signext_33 = sumpipe1_4;
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum2_2 = add_temp_16[68:0];

  assign add_signext_34 = sumpipe1_5;
  assign add_signext_35 = sumpipe1_6;
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum2_3 = add_temp_17[68:0];

  assign add_signext_36 = sumpipe1_7;
  assign add_signext_37 = sumpipe1_8;
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum2_4 = add_temp_18[68:0];

  assign add_signext_38 = sumpipe1_9;
  assign add_signext_39 = sumpipe1_10;
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum2_5 = add_temp_19[68:0];

  assign add_signext_40 = sumpipe1_11;
  assign add_signext_41 = sumpipe1_12;
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum2_6 = add_temp_20[68:0];

  assign add_signext_42 = sumpipe1_13;
  assign add_signext_43 = sumpipe1_14;
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum2_7 = add_temp_21[68:0];

  assign add_signext_44 = sumpipe1_15;
  assign add_signext_45 = $signed({{5{sumpipe1_16[63]}}, sumpipe1_16});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum2_8 = add_temp_22[68:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        sumpipe2_1 <= 0;
        sumpipe2_2 <= 0;
        sumpipe2_3 <= 0;
        sumpipe2_4 <= 0;
        sumpipe2_5 <= 0;
        sumpipe2_6 <= 0;
        sumpipe2_7 <= 0;
        sumpipe2_8 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe2_1 <= sum2_1;
          sumpipe2_2 <= sum2_2;
          sumpipe2_3 <= sum2_3;
          sumpipe2_4 <= sum2_4;
          sumpipe2_5 <= sum2_5;
          sumpipe2_6 <= sum2_6;
          sumpipe2_7 <= sum2_7;
          sumpipe2_8 <= sum2_8;
        end
      end
    end // temp_process2

  assign add_signext_46 = sumpipe2_1;
  assign add_signext_47 = sumpipe2_2;
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum3_1 = add_temp_23[68:0];

  assign add_signext_48 = sumpipe2_3;
  assign add_signext_49 = sumpipe2_4;
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum3_2 = add_temp_24[68:0];

  assign add_signext_50 = sumpipe2_5;
  assign add_signext_51 = sumpipe2_6;
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum3_3 = add_temp_25[68:0];

  assign add_signext_52 = sumpipe2_7;
  assign add_signext_53 = sumpipe2_8;
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum3_4 = add_temp_26[68:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        sumpipe3_1 <= 0;
        sumpipe3_2 <= 0;
        sumpipe3_3 <= 0;
        sumpipe3_4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe3_1 <= sum3_1;
          sumpipe3_2 <= sum3_2;
          sumpipe3_3 <= sum3_3;
          sumpipe3_4 <= sum3_4;
        end
      end
    end // temp_process3

  assign add_signext_54 = sumpipe3_1;
  assign add_signext_55 = sumpipe3_2;
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum4_1 = add_temp_27[68:0];

  assign add_signext_56 = sumpipe3_3;
  assign add_signext_57 = sumpipe3_4;
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum4_2 = add_temp_28[68:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        sumpipe4_1 <= 0;
        sumpipe4_2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe4_1 <= sum4_1;
          sumpipe4_2 <= sum4_2;
        end
      end
    end // temp_process4

  assign add_signext_58 = sumpipe4_1;
  assign add_signext_59 = sumpipe4_2;
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum5_1 = add_temp_29[68:0];

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        sumpipe5_1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumpipe5_1 <= sum5_1;
        end
      end
    end // temp_process5

  assign sum_final = sumpipe5_1;

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum_final;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // fir_30_32b_fcsd
